### ISSUE TITLE
ASN.1 grammar parse error

### ISSUE THREAD

**Issue by ratskrone** [vlm/asn1c#114]
Dear all,
when checking the syntax correctness of an ASN.1 module I got a **grammar parse error** that I do not understand. Any help is appreciated.

This is my call.

`asn1c -EF ISO_TS_19091.asn`

This is the error message.

> ASN.1 grammar parse error near line 129 (token "IDENTIFIED"): syntax error, unexpected TOK_capitalreference, expecting '}'
Cannot parse "ISO_TS_19091.asn"

[ISO_TS_19091.asn.txt](https://github.com/vlm/asn1c/files/497312/ISO_TS_19091.asn.txt)

The ASN.1 module is attached to the issue in case someone likes to reproduce the error.

I use the following asn1c version.

ASN.1 Compiler, v0.9.27

**Comment by velichkov** [comment]
Hi @ratskrone,

 ```
 128 Reg-ConnectionManeuverAssist    REG-EXT-ID-AND-TYPE ::= { 
 129     {ConnectionManeuverAssist-addGrpC   IDENTIFIED BY addGrpC} ,
 130     ... 
 131 }
```
Unfortunately the asn1c doesn't fully support Information Object Classes yet.
You could try the version from #99. See also #108 #43 #64

**Comment by ratskrone** [comment]
Dir velichkov,
thank you very much for the hint. The version #99 helps indeed. Issue resolved and closed.
