### ISSUE TITLE
Unable to parse SAE J2735_201603 

### ISSUE THREAD

**Issue by AlexTelon** [vlm/asn1c#121]
Hi!

I have tried to compile the SAE J2735 ASN specification and it fails when parsing due to two types of errors, one of which is fixed by running the code from #115 (probably due to #99). 

The other is of the type:
J.ASN
`Name nameExtension {{NAME.thing}}`

```
> ASN.1 grammar parse error near line X (token “}”): syntax error, unexpected ‘}’
  Cannot parse “J.ASN”
```

Related to this, i think, I found this comment elsewhere on the internet:

> “However in the current J2735 standard we now make extensive use of **parametrization** functions as well as UPER encoding. The core issue is that this tool [asn1c] however does not support the parametrization features.The basic reason the committee went this way was to allow a cleaner way for regional extension for this message set, which is expected to be adopted as legal requirement for vehicle safety both in the US and in other countries. We needed a way to separate the legal issues from the evolving technical ones. This was done after debating the harm it might cause some tool chains for many months, and there are many on the committee who are advocates for "VLM asn1c" and hope that it may still be used.”
> - https://sourceforge.net/p/asn1c/discussion/357921/thread/d8758a43/#5137

So my question is if there is any work being done towards adding support for this language feature? How would one go about adding support for that? I might be able as a part of my job to spend some time on this but would like to know more about the nature and scope of the problem so I can report that to my superiors.

**Comment by brchiu** [comment]
Hi, @AlexTelon, 

IMHO, 
1. vlm already opened source code to everyone, you can add any new feature you need on your own.
2. You can ask company which sells ASN.1 compiler as commercial product, for example, [Objective Systems, Inc.](https://www.obj-sys.com/products/asn1c/), whether their product supports this feature you need, if it fit your need, then **buy** their compiler for your purpose.

**Comment by AlexTelon** [comment]
Hi @brchiu 

1. Absolutely, I am aiming to help here. Im asking for if anybody was already working on this and if anyone had some ideas and thoughts on how I would go about adding this new feature.
2. Thanks for the tip, that is an option in case it seems that adding the support needed is too large a task.

**Comment by AlexTelon** [comment]
I have dug deeper into this and I have some thoughts and ideas on how to solve the issue that I would want some input on. 

# Example of the problem
First a reiteration on the problem with an code snippet that fails currently.

```ASN.1
A DEFINITIONS AUTOMATIC TAGS::= BEGIN

TYPE-A-EXTENSION ::= CLASS {
   &id     INTEGER UNIQUE,
   &Type
   } WITH SYNTAX {&Type IDENTIFIED BY &id}

ExtensionContent {TYPE-A-EXTENSION : Set } ::= SEQUENCE {
   extenstionId     TYPE-A-EXTENSION.&id( {Set} ),
   extenstionValue  TYPE-A-EXTENSION.&Type( {Set}{@extenstionId} )
   }
   
   
MessageType ::= SEQUENCE {
    data      INTEGER,   

    optionalData      SEQUENCE (SIZE(1..4)) OF 
                      ExtensionContent {{NAMESPACE.extra}} OPTIONAL, -- line 18, error here on #115
    ...
}

END

NAMESPACE DEFINITIONS AUTOMATIC TAGS::= BEGIN 

extra         NAMESPACE.TYPE-A-EXTENSION ::= { ...  }

END
```
With asn1c #115 you get the following error. Im using #115 but #99 works as well.
```
ASN.1 grammar parse error near line 18 (token "."): syntax error, unexpected '.', expecting '}'
Cannot parse "test_para.ASN"
```

# Proposed solution

To fix this one would ideally want to be able to use the information from NAMESPACE.extra and include that into the produced C-code. One could however (in J2735 at least) safely ignore the parametrization alltogether and put the burden of furfilling the specification on the user in this case. This is similar to what ASN1C from obj-sys seemed to do back in the day from what I could gather from [this whitepaper](http://www.obj-sys.com/docs/ASN1CInfoObjectsWhitePaper.pdf).

> "In general, ASN1c can recognize when parameterization is being used, but it will only affect the generated code when it causes a type definition to be modified."

>"The current ASN1C methodology of discarding parameters and ignoring information objects sets result in lean code that can be used to accomplish the encoding or decoding of these message types."

To test this I made a small semi-hardcoded preprocessor that removes all instances of the parametrizations as well as their definitions and replace them with the base type. In this case the information object NAMESPACE.extra is of type TYPE-A-EXTENSTION and it could safely be replaces with that type instead. In this case extra holds no extra information, but if it does its up to the user to make sure to handle it. A better solution is to do this in the compiler and not in a preprocessor, but this is a quick way to try to validate the idea.

# The results from initial trial
The produced ASN from the preprocessor would be:

```ASN.1
A DEFINITIONS AUTOMATIC TAGS::= BEGIN

TYPE-A-EXTENSION ::= CLASS {
   &id     INTEGER UNIQUE,
   &Type
   } WITH SYNTAX {&Type IDENTIFIED BY &id}
   
MessageType ::= SEQUENCE {
    data      INTEGER,   

    optionalData      SEQUENCE (SIZE(1..4)) OF 
                      TYPE-A-EXTENSION OPTIONAL,
    ...
}

END

NAMESPACE DEFINITIONS AUTOMATIC TAGS::= BEGIN 

extra         NAMESPACE.TYPE-A-EXTENSION ::= { ...  }
END 
```

Where ExtensionContent is now removed, optionalData is a sequence of TYPE-A-EXTENSION's and NAMESPACE.extra is no longer used at all.

This ASN code compiles successfully with asn1c #99 and #115 and produces the following MessageType.h struct:

```c
/* MessageType */
typedef struct MessageType {
    long     data;
    struct optionalData {
        A_SEQUENCE_OF(TYPE_A_EXTENSION_t) list;
        
        /* Context for parsing across buffer boundaries */
        asn_struct_ctx_t _asn_ctx;
    } *optionalData;
    /*
     * This type is extensible,
     * possible extensions are below.
     */
    
    /* Context for parsing across buffer boundaries */
    asn_struct_ctx_t _asn_ctx;
} MessageType_t;
```

This struct seems to me to be somewhat resonable. There is allowance for our TYPE_A_EXTENSION in there.

# Questions

- Are ther cases where parametrization can not simply be ignored? In other words is this solution something that could work in general?
 
- Is there any issues in the output as you see it? 
 
- Thoughts and comments in general?

**Comment by brchiu** [comment]
hi, @AlexTelon , recently I fixed the paring and compilation problems encountered during processing SAE J2735_201603 ASN.1 file [here](https://github.com/mouse07410/asn1c/pull/18#issuecomment-297648773). However, I don't have sample DSRC message in  binary format to verdict the codec.

I am not sure whether you still need this asn1c or not. Just inform you about it.

Any feedback is welcomed.

**Comment by vlm** [comment]
The asn1c's master branch contains a working example of SAE J2735 which compiles and produces working code.
