### ISSUE TITLE
-fno-constraints emits code with reference to constraint functions

### ISSUE THREAD

**Issue by mattipee** [vlm/asn1c#122]
With 0.9.27, -fno-constraints generates code that fails to compile for me. Visual inspection of master suggests the issue persists there.

The following patch in asn1c_C.c:emit_type_DEF works for me.

```
<       FUNCREF(constraint);

---
>       if(!arg->flags & A1C_NO_CONSTRAINTS)
>           FUNCREF(constraint);
>       else
>           OUT("0,\t/* No check because of -fno-constraints */\n");
```

**Comment by vlm** [comment]
Applied, thanks!
