### ISSUE TITLE
autoreconf: recursion limit of 1024 exceeded

### ISSUE THREAD

**Issue by harmic** [vlm/asn1c#131]
After cloning the git repo, I'm trying to build, but it fails on the first step:

```
$ autoreconf -iv
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I m4
/usr/bin/m4:configure.ac:107: recursion limit of 1024 exceeded, use -L<N> to change it
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: autom4te failed with exit status: 1
autoreconf: aclocal failed with exit status: 1

```

I don't know enough about autoconf to understand how to troubleshoot this. The error message suggests increasing the recursion limit to m4, but I can't see how one passes this option in. In any case 1024 seems pretty deep, maybe something else is wrong...

I'm using Centos 6, which has autoconf 2.63 and automake 1.11.1.

**Comment by velichkov** [comment]
Hi @harmic 

I don't quite understand what the initial problem was and why the autoreconf fails with `recursion limit of 1024 exceeded` on Centos 6 but I decided to rewrite the 64bit test because it was always failing on both 32 and 64 bit systems.

From #132, 89c49eeff8afe214224fad0f5366abb06865095d

```patch
diff --git a/configure.ac b/configure.ac
index 64a37a9..d03b328 100644
--- a/configure.ac
+++ b/configure.ac
@@ -102,14 +102,8 @@ AC_STRUCT_TM
 AC_CHECK_TYPE(intmax_t, int64_t)
 
 dnl Test if we should check features that depend on 64-bitness.
-AC_MSG_CHECKING(size of long is longer than 32 bit)
-AS_VAR_PUSHDEF([WIDE_LONG], [WIDE_LONG])
-AC_COMPILE_IFELSE([AC_LANG_PROGRAM([[#include "confdefs.h"
-#include <sys/types.h>
-]], [[switch (0) case 0: case (sizeof ($1) >= 8):;]])],[WIDE_LONG=yes],[WIDE_LONG=no])
-AC_MSG_RESULT($WIDE_LONG)
-AM_CONDITIONAL([TEST_64BIT], [test x$WIDE_LONG = xyes])
-AS_VAR_POPDEF([WIDE_LONG])
+AC_CHECK_SIZEOF([void *])
+AM_CONDITIONAL([TEST_64BIT], [test "$ac_cv_sizeof_void_p" -eq 8])
 
 dnl For mingw
 AC_SEARCH_LIBS(getopt, iberty)
```

**Comment by joriws** [comment]
I cloned asn1c 30minutes ago (so I should have your patch) but autoconf is stopped with similar result.

I noticed than my clone did not have above patch. I manually entered and now my first stage (autoconf) completes.

**Comment by velichkov** [comment]
Hi @joriws,

> I cloned asn1c 30minutes ago (so I should have your patch)
I noticed than my clone did not have above patch.

This patch will be available once my pull request (#132) gets merged in the master branch and until then you have to manually apply it or you could just checkout my branch with

```
git fetch origin pull/132/head:pr-132
git checkout pr-132
```

**Comment by Jianhui-Wang** [comment]
I tried to build the asn1c code on the latest cygwin environment but run into the similar error

_$ autoreconf -iv
autoreconf-2.69: Entering directory `.'
autoreconf-2.69: configure.ac: not using Gettext
autoreconf-2.69: running: aclocal -I m4
' is already registered with AC_CONFIG_FILES.
/usr/src/ports/autoconf2.5/autoconf2.5-2.69-4.noarch/src/autoconf-2.69/lib/autoconf/status.m4:288: AC_CONFIG_FILES is expanded from...
configure.ac:128: the top level
autom4te-2.69: /usr/bin/m4 failed with exit status: 1
aclocal-1.15: error: echo failed with exit status: 1
autoreconf-2.69: aclocal failed with exit status: 1_

**Comment by keskintaylan** [comment]
> I tried to build the asn1c code on the latest cygwin environment but run into the similar error
> 
> _$ autoreconf -iv autoreconf-2.69: Entering directory `.' autoreconf-2.69: configure.ac: not using Gettext autoreconf-2.69: running: aclocal -I m4 ' is already registered with AC_CONFIG_FILES. /usr/src/ports/autoconf2.5/autoconf2.5-2.69-4.noarch/src/autoconf-2.69/lib/autoconf/status.m4:288: AC_CONFIG_FILES is expanded from... configure.ac:128: the top level autom4te-2.69: /usr/bin/m4 failed with exit status: 1 aclocal-1.15: error: echo failed with exit status: 1 autoreconf-2.69: aclocal failed with exit status: 1_

same here
