### ISSUE TITLE
-fincludes-quoted option

### ISSUE THREAD

**Issue by katatonia67** [vlm/asn1c#139]
Hi!
I'm trying to use asn1c generated files with my custom Makefile. The problem in -fincludes-quoted flag.
Some of generated source files still use angle quotes instead of double. And should add include path in gcc to compile asn1 generated files. Is there a another solution for this?

**Comment by katatonia67** [comment]
It seems that some of support files(encoders and decoders) doesn't generated but actually copied from templates(/usr/local/share/asn1c)... that's why -fincludes-quoted option doesn't affect on this files

**Comment by vlm** [comment]
Yes. You can use the `-S` flag to asn1c to switch templates to your own modified version.
