### ISSUE TITLE
asn1c: Decoding long fixed-length OCTET STRING fails

### ISSUE THREAD

**Issue by andrepuschmann** [vlm/asn1c#142]
Hey,
I've discovered an issue in decoding an APER-encoded long fixed-length OCTET STRING. The problem seems to be in the handling of the align bits for lengths > two octets. Commenting out that check (see last commit in the example below hides the issue). After looking at the appropriate section in X.691 I am unsure about the correct way of handling it though. I've compiled a small example [here](https://github.com/andrepuschmann/asn1c_test_mini) that shows the issue. It only decodes the message correctly with the changes mentioned above.

I am using the [Mouse07410's asn1c fork](https://github.com/mouse07410/asn1c) for generating the code (but all other APER-enabled forks seem to have the same or similar code).

Would be nice if some of the experts could comment on this issue. Let me know if you need anything else.

Thanks
Andre

**Comment by mouse07410** [comment]
Unfortunately, your example is 2800+ files - infeasible to track.

Could you point at a specific line (or a few lines) in the `asn1c` code that appears to cause problems, and the *exact* fix that appears to remedy the situation?

**Comment by ikarso** [comment]
@mouse07410 its in skeleton/OCTET_STRING.c  https://github.com/andrepuschmann/asn1c_test_mini/commit/6dce9f82e3dfd0a0160ecff3f9f1f86b053ef3f5

Page 27
https://www.itu.int/rec/dologin_pub.asp?lang=e&id=T-REC-X.691-201508-I!!PDF-E&type=items

will look at it during the weekend

**Comment by mouse07410** [comment]
@ikarso thank you for looking into this. PER is not the easiest thing to get right. Your help would be greatly appreciated. 

@andrepuschmann can you try branch 115 of my fork, and tell us if it exhibits the same problem?

**Comment by velichkov** [comment]
Hi @andrepuschmann,

Are you sure that the sib1_payload_tx contains a valid message?
I was not able to decode it using wireshark, [oss](http://asn1-playground.oss.com/) and [marben](http://www.marben-products.com/asn.1/services/decoder-asn1-lte.html) online tools. It seems to be truncted

**Comment by mouse07410** [comment]
I trust OSS tools.

**Comment by velichkov** [comment]
Hi @andrepuschmann,

From 3GPP TS 36.331 version 13.3.0 Release 13
> Transfer syntax for RRC PDUs is derived from their ASN.1 definitions by use of **Packed Encoding Rules, unaligned** as specified in ITU-T Rec. X.691 [15].

Right now you are using `aper_decode` but you should use `uper_decode` instead. After changing it your test succeed.

```
./asn1test_mini 
Buffer size:208
Consumed 160 bits.
BCCH-DL-SCH-Message-NB ::= {
    message: SystemInformationBlockType1-NB ::= {
        hyperSFN-MSB-r13: DD
        cellAccessRelatedInfo-r13: cellAccessRelatedInfo-r13 ::= {
            plmn-IdentityList-r13: PLMN-IdentityList-NB-r13 ::= {
                PLMN-IdentityInfo-NB-r13 ::= {
                    plmn-Identity-r13: PLMN-Identity ::= {
                        mcc: MCC ::= {
                            2
                            1
                            4
                        }
                        mnc: MNC ::= {
                            0
                            1
                        }
                    }
                    cellReservedForOperatorUse-r13: 1
                }
            }
            trackingAreaCode-r13: 02 18
            cellIdentity-r13: 14 37 43 E0
            cellBarred-r13: 1
            intraFreqReselection-r13: 0
        }
        cellSelectionInfo-r13: cellSelectionInfo-r13 ::= {
            q-RxLevMin-r13: -68
            q-QualMin-r13: -23
        }
        freqBandIndicator-r13: 20
        eutraControlRegionSize-r13: 2
        nrs-CRS-PowerOffset-r13: 4
        schedulingInfoList-r13: SchedulingInfoList-NB-r13 ::= {
            SchedulingInfo-NB-r13 ::= {
                si-Periodicity-r13: 3
                si-RepetitionPattern-r13: 1
                sib-MappingInfo-r13: SIB-MappingInfo-NB-r13 ::= {
                }
                si-TB-r13: 4
            }
            SchedulingInfo-NB-r13 ::= {
                si-Periodicity-r13: 5
                si-RepetitionPattern-r13: 1
                sib-MappingInfo-r13: SIB-MappingInfo-NB-r13 ::= {
                    0
                }
                si-TB-r13: 0
            }
        }
        si-WindowLength-r13: 4
        systemInfoValueTagList-r13: SystemInfoValueTagList-NB-r13 ::= {
            3
            2
        }
    }
}
```

**Comment by andrepuschmann** [comment]
Hi @velichkov,
very good catch! I must have overlooked that, thanks for spotting this stupid mistake I made. That's also why removing the code handling the alignment made it work ;-)
Thanks everyone

**Comment by andrepuschmann** [comment]
I mark the issue closed as also mainline asn1c decodes it correctly. Thanks again.
