### ISSUE TITLE
Decode LTE RRC BCCH-BCH-Message Failed

### ISSUE THREAD

**Issue by yangchao007** [vlm/asn1c#149]
Hi all, 
        I used v0.9.28 to decode LTE RRC BCCH-BCH-Message data:  a87c00, and is is decoded as following:

![image](https://cloud.githubusercontent.com/assets/27660107/25122704/7b669a3c-2458-11e7-8a63-8127788b7103.png)

but it is correctly decoded :
BCCH-BCH-Message ::= 
{
    message 
    {
        dl-Bandwidth n100,
        phich-Config 
        {
            phich-Duration normal,
            phich-Resource one
        }
        systemFrameNumber '00011111'B,
        spare '00000000 00'B
    }
}

Please kindly give me some idea about this.
Appreciate for your valuable suggestion.

regards,
ccyang.

**Comment by yangchao007** [comment]
BCCH-BCH-Message ::= 
{
    message 
    {
        dl-Bandwidth n100,
        phich-Config 
        {
            phich-Duration normal,
            phich-Resource one
        }
        systemFrameNumber '00011111'B,
        spare '00000000 00'B
    }
}

**Comment by brchiu** [comment]
hi @yangchao007 ,

I use the newest cloned repository to rebuild asn1c.

Then I use LTE-RRC 14.2.0's asn.1 to generate encoder/decoder and parse your `A87C00` message with the following command line :

```
./lte-rrc-dump -iper -oxer -p BCCH-BCH-Message ./bch.per
```
I get the following XER output

```
<BCCH-BCH-Message>
    <message>
        <dl-Bandwidth><n100/></dl-Bandwidth>
        <phich-Config>
            <phich-Duration><normal/></phich-Duration>
            <phich-Resource><one/></phich-Resource>
        </phich-Config>
        <systemFrameNumber>
            00011111
        </systemFrameNumber>
        <schedulingInfoSIB1-BR-r13>0</schedulingInfoSIB1-BR-r13>
        <spare>
            00000
        </spare>
    </message>
</BCCH-BCH-Message>
```
Looks not too bad.

Could you try to use clone the newest repository instead of 0.9.28 archived file (2014-Sep-17) which is a little old one.

**Comment by MaVapo** [comment]
hi @brchiu  I already installed asn1c-0.9.28.tar.gz.  but I can not find rrc-dump anywhere in my system.
Please kindly give me some idea about this.

**Comment by brchiu** [comment]
@MaVapo, 

`rrc-dump` is an example program under `examples/sample.source.RRC`, you should change working directory to it then invoke `make` to generate C file and compile them into `rrc-dump`. 

Currently only RRC of 25.331's version (i.e. for WCDMA) is available in examples.

I will submit a PR to add 36.331 to examples directory. But since I am not sure whether there is any license issue, as @vlm stated in `rrc-7.1.0.asn1` as following, so I only put the Makefile in my PR.
If you do want 36.331's asn1 file, you have to extract them on your own. 

```
/*
 * Radio Resource Control Technical Specification ASN.1 module.
 * 3GPP 25.331 (TS 125 331) (ETSI ref RTS/TSGR-0225331v710) [2006-06]
 * Extracted and verified by Lev Walkin <vlm@lionet.info>
 *
 * DO NOT REDISTRIBUTE. Obtain your own copy of 3GPP RRC specification
 * if you need to create products based on this RRC ASN.1 module.
 *
 * The ETSI has granted me the right to reproduce this ASN.1 RRC
 * (Radio Resource Control) module as part of asn1c provided that I insert
 * the following paragraph:
 *
 *   3GPP™ TSs and TRs are the property of ARIB, ATIS, ETSI, CCSA, TTA and TTC
 *   who jointly own the copyright in them. They are subject to further
 *   modifications and are therefore provided to you "as is" for information
 *   purposes only. Further use is strictly prohibited.
 */
```

**Comment by MaVapo** [comment]
Thanks for reply @brchiu  .I also assume there is a program under examples/sample.source.RRC
 but under this folder I can't find any file is named rrc-dump
![Uploading QQ截图20170421161000.png…]()

**Comment by brchiu** [comment]
@MaVapo 

You have to **build** this `rrc-dump` by invoking `make` under `examples/sample.source.RRC` directory **on your own**.

**Comment by mouse07410** [comment]
@brchiu and if you're submitting this PR - feel free to make one for my fork too. ;-)

**Comment by yangchao007** [comment]
@brchiu  I used clone the newest repository from https://github.com/vlm/asn1c.git,  and still could decode BCH Message correctly, could you give me some idea?

**Comment by brchiu** [comment]
I am really confused.
You mean it can be 'correctly' or 'incorrectly' decoded ? I know we are not native English users,  however, to express question as accurate as possible still be necessary.

Perhaps your BCH data is of incorrect format ?
Is it taken from log of field data ? Or you construct it on your own ?

Please upload it to somewhere for example Dropbox or Google Drive… then give the link here.

**Comment by velichkov** [comment]
Hi @yangchao007 

> I used clone the newest repository from https://github.com/vlm/asn1c.git,

Clone the https://github.com/mouse07410/asn1c/ and try with it. After building it don't forget to regenerate all C sources from the asn1 files using this version. This is the `newest cloned repository` that @brchiu  was referring to in the previous comments. I confirm that this version successfully decodes your message.

**Comment by yangchao007** [comment]
@brchiu I am very sorry for it. I got my BCH data from the website. Maybe it is incorrect format. Thank you for your kind help.
@velichkov Thanks very much. I will try it.

**Comment by yangchao007** [comment]
@brchiu Yes, you are right. My BCH data is  incorrect format.  It can be decoded correctly.  Thank you.
@velichkov Thank you for your kind help.  I will continue to study it.
