### ISSUE TITLE
CONTEXT-SPECIFIC tags encoded as PRIVATE

### ISSUE THREAD

**Issue by speidy** [vlm/asn1c#152]
Hello

I have passed the following asn.1 definition file to asn1c (built from latest git master branch), and it seems like the CONTEXT-SPECIFIC tags are wrongly encoded as PRIVATE:

```
CredSSP DEFINITIONS ::= BEGIN

TSRequest ::= SEQUENCE {
	version 	[0] INTEGER,
	negoTokens 	[1] NegoData OPTIONAL,
	authInfo 	[2] OCTET STRING OPTIONAL,
	pubKeyAuth 	[3] OCTET STRING OPTIONAL,
	errorCode 	[4] INTEGER OPTIONAL
}
.
. (more definitions...)
.
END
```
As far as i know the [number] symbols should make CONTEXT-SPECIFIC. but as far as i'm new to ASN.1 encoding i might be wrong.
Anyway, i got all the internal tags private, and i want them to be context-specific.

Can anyone help?

Thx,Idan.

**Comment by velichkov** [comment]
Hi Idan,

> As far as i know the [number] symbols should make CONTEXT-SPECIFIC. but as far as i'm new to ASN.1 encoding i might be wrong.

Correct.

> Anyway, i got all the internal tags private, and i want them to be context-specific.

I just tried with your ASN and the tags are encoded correctly as Context Specific

 30 0a **a0** 03 02 01 01 **a4** 03 02 01 2a

**Comment by speidy** [comment]
@velichkov Thanks for replying.
I did my tests using [ASN1 Editor](https://www.sysadmins.lv/projects/asn1editor/default.aspx) utility.
It turns out my encoded buffer was extra  padded, that confused ASN1 Editor- It didn't show the context specific tags because of the padding.
