### ISSUE TITLE
why don't padding 0x00 when INTEGER's first char value >= 0x80?

### ISSUE THREAD

**Issue by chn475111** [vlm/asn1c#165]
why donn't asn1c padding 0x00 before INTEGER value, when INTEGER's first character >= 0x80?

**Comment by chn475111** [comment]
e.g.
30 44 02 20 dc df 4e 6f 8b cb 06 f7 91 31 ad f2
2e 3f 39 a2 fa 53 92 52 aa 64 22 cb 16 9c 7e 76
1c 3d 5d 51 02 20 22 8a be e9 7c 01 83 99 6d 2e
fc a9 c1 0a 0e 81 d0 c2 62 ed e4 5b 5e c1 2d bf
5c 36 44 c9 b0 8e

should be

30 45 02 20 00 dc ... and so on.

**Comment by velichkov** [comment]
Hi @chn475111,

Could you share the ASN.1 definitions and the encoding?

**Comment by chn475111** [comment]
Hi, @velichkov 
it's my module

Module DEFINITIONS ::= BEGIN
Signature    ::= SEQUENCE {
    r               INTEGER,                    
    s               INTEGER                     
}
END

**Comment by chn475111** [comment]
`int sm2sign_encode(unsigned char *in , int inlen, unsigned char *out, int *outlen)
{
    asn_enc_rval_t enc = {
        .encoded = -1,
        .failed_type = NULL
    };
    SM2Signature_t *sm2encode = NULL;

    if(*outlen < inlen + 6)
        return -1;

    sm2encode = (SM2Signature_t*)malloc(1*sizeof(SM2Signature_t));
    if(sm2encode == NULL)
    {
        fprintf(stderr, "%s:%d - %d:%s\n", __FILE__, __LINE__, errno, strerror(errno));
        goto ErrP;
    }
    memset(sm2encode, 0, 1*sizeof(SM2Signature_t));

    sm2encode->r.buf = (unsigned char*)malloc(32*sizeof(unsigned char));
    if(sm2encode->r.buf == NULL)
    {
        fprintf(stderr, "%s:%d - %d:%s\n", __FILE__, __LINE__, errno, strerror(errno));
        goto ErrP;
    }
    memset(sm2encode->r.buf, 0, 32*sizeof(unsigned char));

    //r
    sm2encode->r.size = 32;
    memcpy(sm2encode->r.buf, &in[0], 32);

    sm2encode->s.buf = (unsigned char*)malloc(32*sizeof(unsigned char));
    if(sm2encode->s.buf == NULL)
    {
        fprintf(stderr, "%s:%d - %d:%s\n", __FILE__, __LINE__, errno, strerror(errno));
        goto ErrP;
    }
    memset(sm2encode->s.buf, 0, 32*sizeof(unsigned char));

    //s
    sm2encode->s.size = 32;
    memcpy(sm2encode->s.buf, &in[32], 32);

    enc = der_encode_to_buffer(&asn_DEF_SM2Signature, sm2encode, out, *outlen);
    if(enc.encoded == -1)
    {
        fprintf(stderr, "%s:%d - %s\n", __FILE__, __LINE__, enc.failed_type ? enc.failed_type->name : "unknown");
        goto ErrP;
    }

    *outlen = enc.encoded;
    if(sm2encode)
    {
        if(sm2encode->r.buf);
            free(sm2encode->r.buf);
        if(sm2encode->s.buf);
            free(sm2encode->s.buf);
        free(sm2encode);
    }
    return 0;
ErrP:
    if(sm2encode)
    {
        if(sm2encode->r.buf);
            free(sm2encode->r.buf);
        if(sm2encode->s.buf);
            free(sm2encode->s.buf);
        free(sm2encode);
    }
    return -1;
}`

**Comment by chn475111** [comment]
hi @velichkov ,
wish your reply.
thank you.

**Comment by velichkov** [comment]
> why donn't asn1c padding 0x00 before INTEGER value, when INTEGER's first character >= 0x80?

It does not because the integer could be negative as well and in this case a zero byte should not be added.

```
sm2encode->r.size = 32;
memcpy(sm2encode->r.buf, &in[0], 32);
```
You are encoding really big numbers and thats why you have to specify them as buffers and you can't specify the sign.

```
Signature ::= SEQUENCE {
r INTEGER,
s INTEGER
}
```
A more appropriate ASN.1 type in your case could be OCTET STRING

**Comment by velichkov** [comment]
```
Signature ::= SEQUENCE {
r OCTET STRING,
s OCTET STRING
}
```

**Comment by chn475111** [comment]
i got it.
thank you.
it's beacause my r/s is in finite field and they are non-negative,
i will operate them by myself.
thank you again and again.

**Comment by mouse07410** [comment]
@velichkov is right. Apparently your non-negative integers look exactly like negative to the DER encoder.  ASN.1 does not define unsigned integers. It allows constraints - so theoretically one could define your SM2 signature as
```
Signature ::= SEQUENCE {
   r INTEGER (0..subgroup_order),
   s INTEGER (0..subgroup_order) 
}
```
where `subgroup_order` is the max value the finite field elements could have. 

But in practice `asn1c` does not (yet) support constraints of such magnitude. @velichkov here's another reason to add support for "almost unlimited" constraints, switching to INTEGER_t type.

@chn475111 you may want to take a look at how OpenSSL represents and encodes ECDSA signatures. And you'd have to tweak the asn1c-provided encoder if you want to use asn1c for this.

**Comment by chn475111** [comment]
@mouse07410 
yes, you are right;
and i have tweaked my Signature.
thank you.

**Comment by vlm** [comment]
The INTEGERs in PKIX1 signatures are a bit broken and probably better to be replaced with `[UNIVERSAL 2] IMPLICIT OCTET STRING` to mimic INTEGER during encoding but make it easier during handling. This way you can treat them as bytes instead of potentially signed numbers. _Not clear what it would break though._

Otherwise the industry treats big integers as unsigned, and ASN.1 treats big INTEGERs as signed.

This is really a problem in ASN.1 spec of PKIX1, and a conforming ASN.1 compiler **has** to treat it in a somewhat buggy way.
