### ISSUE TITLE
[BER file with "0x00" filler  inside] not able to unber correctly

### ISSUE THREAD

**Issue by RFDonovan** [vlm/asn1c#175]
Hi everyone,

Using the v0.9.28, I am not able to decode correctly a ber file, only the first 8 to 10 records and end up with:
```
<absent>
CDRERR.ber: Decode failed past byte 1447: Input processing error
```

By using **unber**, the same thing happen and I always end up with the following lines:

```
...
<P O="8169" T="[UNIVERSAL 0]" TL="2" V="0"></P>
<P O="8171" T="[UNIVERSAL 0]" TL="2" V="0"></P>
<P O="8173" T="[UNIVERSAL 0]" TL="2" V="0"></P>
<P O="8175" T="[UNIVERSAL 0]" TL="2" V="0"></P>
<P O="8177" T="[UNIVERSAL 0]" TL="2" V="0"></P>
<P O="8179" T="[UNIVERSAL 0]" TL="2" V="0"></P>
<P O="8181" T="[UNIVERSAL 0]" TL="2" V="0"></P>
<P O="8183" T="[UNIVERSAL 0]" TL="2" V="0"></P>
<P O="8185" T="[UNIVERSAL 0]" TL="2" V="0"></P>
<P O="8187" T="[UNIVERSAL 0]" TL="2" V="0"></P>
<P O="8189" T="[UNIVERSAL 0]" TL="2" V="0"></P>
CDRERR.ber: Fatal error decoding value length at 8192
```

I was searching for identical issue in the web for a week and the only one I found is [this](https://sourceforge.net/p/asn1c/discussion/357921/thread/578b1089/) but the discussion ends up.

Can someone pinpoint me to the right direction?

**Comment by RFDonovan** [comment]
OK so pushing a little bit further in my research.
Using xxd to print the hexa of the BER file I noticed that the input file contains sometimes a lot of  "0000 0000" in between, kind of a void filling. I'm pretty sure it is the reason but still I don't know yet how to handle them.
If someone know how to handle those fillers? 
What I mean is **how to actually prevent the decoder to take those bytes into consideration**

**Comment by RFDonovan** [comment]
I was finally able to decode the BER file by removing the 0x00 filler within it.
For those who (probably will) get the same error, this is what I did:
I used the command sed as bellow:
`sed -i.bak 's/\x00\x84\x01\x00\x00*/\x00\x84\x01\x00/g' file.ber`

I noticed that the pattern 0084 0100 always come before the filler. I **just remove the 00** et voilà :)

Thanks a lot for open-sourcing this ASN1C! It's a huge help.

**Comment by igbayilola** [comment]
Hi everyone,
Using the v0.9.29, I am not able to unber correctly a ber file. I get the following error:

`<P O="16373" T="[UNIVERSAL 0]" TL="2" V="0"></P>
<P O="16375" T="[UNIVERSAL 0]" TL="2" V="0"></P>
<P O="16377" T="[UNIVERSAL 0]" TL="2" V="0"></P>
<P O="16379" T="[UNIVERSAL 0]" TL="2" V="0"></P>
<P O="16381" T="[UNIVERSAL 0]" TL="2" V="0"></P>
CCNCDR.ber: Fatal error decoding value length at 16393`

I was searching for identical issue and I found your issue. Following it, I also find that there is a lot of "0000 0000" in between, kind of a void filling. But counter to that case, my file doesn’t fit to any known pattern.
Then, I have two questions:

- how to prevent the decoder to take those bytes into consideration?
- Or how to clean the file?

Thanks,
