### ISSUE TITLE
TLV records spaced out by "xFF" fillers cannot be read by ber_decode()

### ISSUE THREAD

**Issue by wiltonlee** [vlm/asn1c#18]
Encounter ASN.1 BER encoded files with TLV records seperated by "\xFF" cannot be decoded either by unber or function ber_decode() with error "Fatal error decoding tag at xxxx" and "Decode failed past byte XXX: Input processing error"

The TLV records are packed  into 2048 bytes block size with one file containing many 2048 blocks. If each block has remaining space left after packing the TLV records, it wil be filled with "\xFF" before the next block starts.   Once the decoder reach this point, it will crash out with the above error meessage. 

Is there a way for the ber_decoder() function to skip over this gap fillers and move the next start of record ?

**Comment by igbayilola** [comment]
@wiltonlee @vlm Sorry, how did you solve this please?
