### ISSUE TITLE
compilation failed after commit e9050cc

### ISSUE THREAD

**Issue by DanyaFilatov** [vlm/asn1c#189]
@vlm Compilation using cygwin failed after today's commits.

  CC       asn1print.lo
  CCLD     libasn1print.la
libtool:   error: object name conflicts in archive: libasn1print/.libs/libasn1print.lax/libasn1common.a  and libasn1common/.libs/libasn1common.a

Tried with a clean project.

**Comment by vlm** [comment]
Would you please try again and attempt to fix if you can. Please be sure to use a fresh checkout of asn1c to resolve potential issues with existing filesystem junk.

**Comment by DanyaFilatov** [comment]
This is exactly what I did before submit the ussue: fresh checkout and execute all build steps.
Will try to fix it asap.

**Comment by DanyaFilatov** [comment]
Sorry, it was a strange cygwin misconfiguration. Closed now
