### ISSUE TITLE
PKIX1 sample broken

### ISSUE THREAD

**Issue by pzb** [vlm/asn1c#193]
Using a fresh checkout (at 14fd3e5a89d137f094d7b477aa55a83aae9451f2), the PKIX1 sample has an error:

```
$ ./x509dump sample-Certificate-1.der
sample-Certificate-1.der: Decode failed past byte 4: Input processing error
```

I used the exact same build steps I've used in the past:
```
autoreconf -iv
./configure
make
cd examples/sample.source.PKIX1/
make
```

I wasn't able to get good answer of when this broken from git bisect, as there are points where the example wouldn't build at all.

**Comment by vlm** [comment]
Fixed, thank you!
