### ISSUE TITLE
ENUMERATED produces the same identifier for all enums

### ISSUE THREAD

**Issue by ringlej** [vlm/asn1c#200]
The latest master build of asn1c will produce the same identifier for all enums in ENUMERATED.
Here is an example:
```code
TestModule DEFINITIONS IMPLICIT TAGS ::=
BEGIN

Foo ::= ENUMERATED {
        bar     (1),
        xyzzy   (2),
        ziggy   (3)
}

END
```
This will produce Foo.h:
```code
/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TestModule"
 *      found in "../enum.asn1"
 */

#ifndef _Foo_H_
#define _Foo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Foo {
        Foo_Foo = 1,
        Foo_Foo = 2,
        Foo_Foo = 3
} e_Foo;

/* Foo */
typedef long     Foo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Foo;
asn_struct_free_f Foo_free;
asn_struct_print_f Foo_print;
asn_constr_check_f Foo_constraint;
ber_type_decoder_f Foo_decode_ber;
der_type_encoder_f Foo_encode_der;
xer_type_decoder_f Foo_decode_xer;
xer_type_encoder_f Foo_encode_xer;

#ifdef __cplusplus
}
#endif

#endif  /* _Foo_H_ */
#include <asn_internal.h>
```

**Comment by ringlej** [comment]
I did a git bisect, and found that the commit that introduced this bug is:
```
b46156d9be5569eb51965bafcd2b58d9c8bc9c38 is the first bad commit
commit b46156d9be5569eb51965bafcd2b58d9c8bc9c38
Author: Lev Walkin <vlm@lionet.info>
Date:   Tue Sep 5 02:53:05 2017 -0700

    naming abstraction

:040000 040000 8b9c3a0d282a41e99653010c523f08ac30079096 254852dcd73f508c6dff30a39dda1a6241de2d1f M      libasn1compiler
:040000 040000 2b17ec0390afb3b854ab6c45c4437a915ffa52bb 873042bbe726d6f432803d481c2056cbf46674ca M      tests
```

**Comment by vlm** [comment]
Can't reproduce. How do you compile it? My latest master:

```
[vlm@nala:~]> cat test.asn1; echo ===; ./asn1c/asn1c -P test.asn1  | grep Foo_bar
TestModule DEFINITIONS IMPLICIT TAGS ::=
BEGIN

Foo ::= ENUMERATED {
        bar     (1),
        xyzzy   (2),
        ziggy   (3)
}

END

===
	Foo_bar	= 1,
[vlm@nala:~]> 
```

**Comment by HongDols** [comment]
Me, too. Same situation.

This is my asn.1 document.
SteeringWheelAngleConfidence ::= ENUMERATED {
   unavailable (0), -- B'00  Not Equipped with Wheel angle
                    -- or Wheel angle status is unavailable
   prec2deg    (1), -- B'01  2 degrees
   prec1deg    (2), -- B'10  1 degree
   prec0-02deg (3)  -- B'11  0.02 degrees
   }

Next is compile result.
typedef enum SteeringWheelAngleConfidence {
	SteeringWheelAngleConfidence_SteeringWheelAngleConfidence	= 0,
	SteeringWheelAngleConfidence_SteeringWheelAngleConfidence	= 1,
	SteeringWheelAngleConfidence_SteeringWheelAngleConfidence	= 2,
	SteeringWheelAngleConfidence_SteeringWheelAngleConfidence	= 3
} e_SteeringWheelAngleConfidence;

A enum type has a bug.

**Comment by ringlej** [comment]
I just rebased to the latest master and I'm still having the same problem:
```
$ cat ../enum.asn1; echo ===; asn1c ../enum.asn1 2>/dev/null ; grep "typedef enum Foo" -A4 Foo.h 
TestModule DEFINITIONS IMPLICIT TAGS ::=
BEGIN

Foo ::= ENUMERATED {
        bar     (1),
        xyzzy   (2),
        ziggy   (3)
}

END

===
typedef enum Foo {
        Foo_Foo = 1,
        Foo_Foo = 2,
        Foo_Foo = 3
} e_Foo;
```

**Comment by HongDols** [comment]
I chagne asn1c_naming.c file temprory.

const char *
c_member_name(arg_t *arg, asn1p_expr_t *expr) {
    static abuf ab;
    
    abuf_clear(&ab);
    
    //before
    //abuf_printf(&ab, "%s_%s", c_name_impl(arg, 0).base_name), asn1c_make_identifier(0, expr, 0)) ;
    //after :
    abuf_printf(&ab, "%s", c_name_impl(arg, 0).base_name);
    abuf_printf(&ab, "_%s", asn1c_make_identifier(0, expr, 0));
return ab.buffer;
}

const char *
c_presence_name(arg_t *arg, asn1p_expr_t *expr) {
    static abuf ab;

    abuf_clear(&ab);

    if(expr) {
        //before
        //abuf_printf(&ab, "%s_PR_%s", c_name_impl(arg, 0).base_name, asn1c_make_identifier(0, expr, 0));
        //after
        abuf_printf(&ab, "%s", c_name_impl(arg, 0).base_name);
        abuf_printf(&ab, "_PR_%s", asn1c_make_identifier(0, expr, 0));
    } else {
        abuf_printf(&ab, "%s_PR_NOTHING", c_name_impl(arg, 0).base_name);
    }

    return ab.buffer;
}

**Comment by DanyaFilatov** [comment]
I confirm the bug.

Foo.asn: 
TestModule DEFINITIONS IMPLICIT TAGS ::=
BEGIN
Foo ::= ENUMERATED {
        bar     (1),
        xyzzy   (2),
        ziggy   (3)
}
END

## asn1c -P Foo.asn

/*** <<< INCLUDES [Foo] >>> ***/
#include <NativeEnumerated.h>
/*** <<< DEPS [Foo] >>> ***/
typedef enum Foo {
	Foo_Foo	= 1,
	Foo_Foo	= 2,
	Foo_Foo	= 3
} e_Foo;
/*** <<< TYPE-DECLS [Foo] >>> ***/
...

Compiled using cygwin64 with today's snapshot of master branch, commit 77f65c9

**Comment by ringlej** [comment]
@vlm , I think @HongDols  is on the right track. The problem is coming from the fact that the function `c_member_name()` is calling both `c_name_impl()` and `asn1c_make_identifier()` and before their return values are passed into `abuf_printf()`. The function `asn1c_make_identifier()` has a static buffer `storage` that is used, but the call path in `c_name_impl()` also calls `asn1c_make_identifier()` via `construct_base_name()` and therefore replaces the content of the static `storage` buffer. By the time `abuf_printf()` gets the two buffers, they are the same.

**Comment by vlm** [comment]
Fixed, thank you all!

**Comment by ringlej** [comment]
@vlm Your fix in commit https://github.com/vlm/asn1c/commit/c66ccbcae5376ac1ee9717420c3ade53e803edfe only fixes the issue in c_presence_name(), but the problem is also in c_member_name() too

**Comment by vlm** [comment]
@ringlej , fixed, thanks!
