### ISSUE TITLE
redeclaration of enumerator

### ISSUE THREAD

**Issue by wanxs-git** [vlm/asn1c#201]
I use asn1c to build 3gpp 36331-bh0. Got the c and h file.
use make -f Makefile.am.sample build the C file.and get PHICH-Config.h:25:2: error: redeclaration of enumerator ‘PHICH_Config__phich_Duration_phich_Duration’
how can i fix the error!

**Comment by vlm** [comment]
Please provide a minimal example.

**Comment by vlm** [comment]
Fixed, thank you!
