### ISSUE TITLE
File dependencies bug in OER

### ISSUE THREAD

**Issue by DanyaFilatov** [vlm/asn1c#204]
Not all common files copied from skeletons in OER generation for

```
FooModule DEFINITIONS IMPLICIT TAGS ::=
BEGIN
Foo ::= ENUMERATED {
        bar     (1),
        xyzzy   (2),
        ziggy   (3)
}
END
```
This requires **OPEN_TYPE_oer.c** and **constr_SEQUENCE_oer.c** (I don't know why), but does not copy **OPEN_TYPE.h**, **constr_CHOICE.h** and **constr_SEQUENCE.h**
As a result, generated code can not be compiled.

**Comment by vlm** [comment]
Appears to have been fixed for some time now.
