### ISSUE TITLE
incompatible with libasn1c

### ISSUE THREAD

**Issue by wangaohui** [vlm/asn1c#205]
I find asn1c is not compatible with libasn1c, some structures is different such as asn_TYPE_member_s, asn_TYPE_descriptor_t. 
I want to use asn1c to produce the headers and sources, and link with libasn1c, how could i do this?

**Comment by vlm** [comment]
@wangaohui, what is libasn1c?

**Comment by wangaohui** [comment]
here, https://github.com/osmocom/libasn1c
could you give me some suggestions? @vlm

**Comment by vlm** [comment]
I can't afford to support other people's projects, sorry. Ask them to regenerate the project with the newest compiler?

In any case, you can build `libasn1c` yourself by just compiling everyting in the `skeletons` directory except for `converter-sample.c` and place it into a library.

**Comment by wangaohui** [comment]
thanks :) @vlm
