### ISSUE TITLE
Enumerated decoding for PER prints integer value, not explicit meaning

### ISSUE THREAD

**Issue by dbressan2** [vlm/asn1c#206]
I attempted to use asn1c version 0.9.28. I encountered one issue in the way enumerated are decoded. 

If we take the following ASN.1 definition (from 3GPP LTE RRC standard): 

          prioritisedBitRate  ENUMERATED {
               kBps0,
               kBps8,
               kBps16,
               kBps32,
               kBps64,
               kBps128,
               kBps256,
               infinity,
               kBps512-v1020,
               kBps1024-v1020,
               kBps2048-v1020,
               spare5,
               spare4,
               spare3,
               spare2,
               spare1
          },

asn1c 0.9.22 decodes as: prioritisedBitRate: 2 (kBps16)
asn1c 0.9.28 decodes as: prioritisedBitRate: 2

The 0.9.22 decoding result is much more informative for end user who does not need to revert to standard definition to understand what value 2 corresponds to. 

After some code inspection, the main difference is as follows: 

•	0.9.22 maps ASN.1 ENUMERATED to DEF_ENUMERATED. Eventually INTEGER__dump from INTEGER.c is called to print the ENUMERATED and both value and corresponding name are printed. 
•	0.9.28 maps ASN.1 ENUMERATED to DEF_NativeEnumerated. Eventually NativeInteger_print from NativeInteger.c is called to print the ENUMERATED but only value is printed. 

What would be the easiest way to fix this issue ? Can we simply bring back the enumeration name in NativeInteger_print ? 
Is there any advantage using DEF_NativeEnumerated rather than DEF_ENUMERATED ? If not, can we configure 0.9.28 to use DEF_ENUMERATED instead ? 

0.9.22

/*
* This type is implemented using ENUMERATED,
* so here we adjust the DEF accordingly.
*/
static void
prioritisedBitRate_4_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
      td->free_struct    = asn_DEF_ENUMERATED.free_struct;
      td->print_struct   = asn_DEF_ENUMERATED.print_struct;
      td->ber_decoder    = asn_DEF_ENUMERATED.ber_decoder;
      td->der_encoder    = asn_DEF_ENUMERATED.der_encoder;
      td->xer_decoder    = asn_DEF_ENUMERATED.xer_decoder;
      td->xer_encoder    = asn_DEF_ENUMERATED.xer_encoder;
      td->uper_decoder   = asn_DEF_ENUMERATED.uper_decoder;
      td->uper_encoder   = asn_DEF_ENUMERATED.uper_encoder;
      if(!td->per_constraints)
            td->per_constraints = asn_DEF_ENUMERATED.per_constraints;
      td->elements       = asn_DEF_ENUMERATED.elements;
      td->elements_count = asn_DEF_ENUMERATED.elements_count;
     /* td->specifics      = asn_DEF_ENUMERATED.specifics;  // Defined explicitly */
}

INTEGER.c

static ssize_t
INTEGER__dump(asn_TYPE_descriptor_t *td, const INTEGER_t *st, asn_app_consume_bytes_f *cb, void *app_key, int plainOrXER) {
      asn_INTEGER_specifics_t *specs=(asn_INTEGER_specifics_t *)td->specifics;
            if(el) {
                  scrsize = el->enum_len + 32;
                  scr = (char *)alloca(scrsize);
                  if(plainOrXER == 0)
                        ret = snprintf(scr, scrsize,
                              "%ld (%s)", accum, el->enum_name);

0.9.28

/*
* This type is implemented using NativeEnumerated,
* so here we adjust the DEF accordingly.
*/
static void
prioritisedBitRate_4_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
      td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
      td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
      td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
      td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
      td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
      td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
      td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
      td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
      td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
      if(!td->per_constraints)
            td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
      td->elements       = asn_DEF_NativeEnumerated.elements;
      td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;  // Defined explicitly */
}

/*
* INTEGER specific human-readable output.
*/
int
NativeInteger_print(asn_TYPE_descriptor_t *td, const void *sptr, int ilevel,
      asn_app_consume_bytes_f *cb, void *app_key) {
      asn_INTEGER_specifics_t *specs=(asn_INTEGER_specifics_t *)td->specifics;
      const long *native = (const long *)sptr;
      char scratch[32]; /* Enough for 64-bit int */
      int ret;

      (void)td;   /* Unused argument */
      (void)ilevel;     /* Unused argument */

      if(native) {
            ret = snprintf(scratch, sizeof(scratch),
                  (specs && specs->field_unsigned)
                  ? "%lu" : "%ld", *native);
            assert(ret > 0 && (size_t)ret < sizeof(scratch));
            return (cb(scratch, ret, app_key) < 0) ? -1 : 0;
      } else {
            return (cb("<absent>", 8, app_key) < 0) ? -1 : 0;
      }
}

Thank you very much for your help 

Best regards 

Dominique Bressanelli

**Comment by vlm** [comment]
Fixed, enjoy!

By the way, debug printing does not adhere to any particular specificaition and can change at any moment. If you want a nice standardized debug, consider using `xer_fprint(XER_F_BASIC)` as a debugging mechanism. It does contain enumerated values in text form.

**Comment by dbressan2** [comment]
Thank you Mr Walkin, the fix is working fine.

I got the latest source code from the trunk and I needed to modify 2 lines for skeletons/INTEGER.c in order to compile (Cygwin, gcc):

Line 152: "%" PRIdMAX " (%s)", value, el->enum_name);
Replaced with: "%d" (%s)", value, el->enum_name);

Line 166: (specs && specs->field_unsigned) ? "%" PRIuMAX : "%" PRIdMAX,
Replaced with: (specs && specs->field_unsigned) ? "%u": "%d",

Not sure what PRIMAX is supposed to do

Thank you very much for your help

Best regards

D. Bressanelli
