### ISSUE TITLE
error: 'MAXFLOAT' undeclared

### ISSUE THREAD

**Issue by ringlej** [vlm/asn1c#212]
Since commit ab1d1e1ea409f3cc16f05279eec3fe3cf54798ba I get this compile error:
```
NativeReal.c: In function ‘NativeReal_random_fill’:
NativeReal.c:525:10: error: ‘MAXFLOAT’ undeclared (first use in this function)
         -MAXFLOAT, MAXFLOAT,
          ^
```

Please replace MAXFLOAT with FLT_MAX that is defined in <float.h>

Thanks

**Comment by vlm** [comment]
Merged, thanks!
