### ISSUE TITLE
How can I use encapsulated structure? (using CONTAINING )

### ISSUE THREAD

**Issue by Regelek** [vlm/asn1c#218]
Hi,

I would like to use CONTAINING in asn1c.
In my example i would like to give values in the Octasd SEQUENCE for version and tsapolicy. I thought i can do it like any other asn1 types.

For example: EncapsulatedContentInfo->eContent.octasd.version
But i don't "see" behind octasd.

Is there any way to reach an encapsulated structure?

Part of my asn1:

EncapsulatedContentInfo ::= SEQUENCE {
       contentType OBJECT IDENTIFIER,
       eContent [0] IMPLICIT SEQUENCE {
              octasd Octasd
       }
}

Octasd ::= OCTET STRING (CONTAINING SEQUENCE {
        version INTEGER,
        tsapolicy OBJECT IDENTIFIER
} )

Thanks, Elek

**Comment by vlm** [comment]
You'll have to do it manually. Create a named structure with SEQUENCE { version INTEGER, tsapolicy OBJECT IDENTIFIER }, encode it and place the bytes into the octasd.{buf,size}.

**Comment by Regelek** [comment]
Thank you for your response!
