### ISSUE TITLE
Porting to arm64-v8a issue

### ISSUE THREAD

**Issue by olegst90** [vlm/asn1c#235]
I'm trying to build and run the code on arm64-v8a using Android NDK. After porting qsort, bsearch and a couple of headers, I managed to build the code. Then, on the device, I do the test to encode and decode a struct, and I get such an **unexpected tag error** during decoding.

On my x86_64 host, the same code works correctly.

Has anybody successfully run asn1c-generated code on 64 bit Android and have you encountered such errors?

**Comment by vlm** [comment]
Can you provide a minimum example? That would be an ASN.1 module and a `main()` function that demonstrates the problem.

**Comment by olegst90** [comment]
I have a structure:



```
/*
Foo ::= [APPLICATION 13] SEQUENCE { 
	f1 UTF8String,
	f2 Bar OPTIONAL,
	f3 UTF8String,
	f4 PrintableString,
	f5 UTF8String OPTIONAL
}
*/
typedef struct Foo {
	UTF8String_t	 f1;
	Bar_t	*f2	/* OPTIONAL */;
	UTF8String_t	 f3;
	PrintableString_t	 f4
	UTF8String_t	*f5	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Foo_t;
```

Then I encode it:

```
    Foo_t *f = calloc(1, sizeof(*f));
    OCTET_STRING_fromString(&f->f1, "Blahblahbla");
    OCTET_STRING_fromString(&f->f3, "ABABAB");
    OCTET_STRING_fromString(&f->f4, "0.0.1");

    char buff[1024] = {0};
    size_t buff_size = sizeof(buff);
    asn_enc_rval_t asnres = der_encode_to_buffer(&asn_DEF_Foo, f, buff, buff_size);
```

and decode:

```
Foo_t *decoded = NULL;
asn_dec_rval_t asnres = ber_decode(0, &asn_DEF_Foo, (void**)&decoded, buff, asnres.encoded);
    if(asnres.code == RC_OK) {
       ...
    } else {
        printf("could not decode\n");
    }
```

On x86_64, it works just fine. On arm, it doesn't decode:

`Unexpected tag [UNIVERSAL 12] (at 3)Expected tag [UNIVERSAL 19] (f4)`

12 is UTF8 string tag, 19 is Printable sring. I don't know why it expects utf string instead of printable one.

Binaries produced by encode are the same on both platforms.

**Comment by olegst90** [comment]
I've just tried the latest release and it works.
