### ISSUE TITLE
Accessing structure member's respective buffer region during decoding?

### ISSUE THREAD

**Issue by olegst90** [vlm/asn1c#248]
I've got a question. I have a structure which has hash of one of it's members calculated over it's ASN.1 representation. Is there a way to know from what part of the buffer the member was decoded? I'm using DER.

**Comment by vlm** [comment]
The DER is defined in a special way that guarantees that if you encode it again you'd get a buffer which corresponds to the original buffer exactly. That is called a "canonical" form. I'd recommend you just encoding the part of the stucture using `asn_encode_to_new_buffer()` and using a hash function over the result.
