### ISSUE TITLE
Q: are PER (UPER) and APER PDUs supposed to be padded, or not?

### ISSUE THREAD

**Issue by mouse07410** [vlm/asn1c#258]
Not a bug - just a question. Is there a rule or a convention that PER PDUs should be padded? By default, should one expect a received PER (UPER) PDU to be padded, or not?

Same question for APER - padded or not by default?

Thanks!

I.e., which of these two would require `-per-nopad` flag, and when? *And apologies for a naive question.*

**Comment by mouse07410** [comment]
@vlm, would you be able to comment?

**Comment by velichkov** [comment]
Hi @mouse07410,

Here are some quotes from [Rec. ITU-T X.691 (08/2015)](https://www.itu.int/rec/dologin_pub.asp?lang=e&id=T-REC-X.691-201508-I!!PDF-E&type=items)

> 7.7
Both BASIC-PER and CANONICAL-PER come in two variants, the ALIGNED variant, and the UNALIGNED variant. __In the ALIGNED variant, padding bits are inserted from time to time to restore octet alignment. In the UNALIGNED variant, no padding bits are ever inserted.__

> 11.1.2 The field-list produced as a result of applying this Recommendation | International Standard to an abstract value of an outermost type shall be used to produce the complete encoding of that abstract syntax value as follows: each field in the field-list shall be taken in turn and concatenated to the end of the bit string which is to form the complete encoding of the abstract syntax value __preceded by additional zero bits for padding as specified below.__
11.1.3 In the __UNALIGNED__ variant of these encoding rules, all fields shall be concatenated __without padding__. If the result of encoding the outermost value is an empty bit string, the bit string shall be replaced with a single octet with all bits set to 0. If it is a non-empty bit string and it is not a multiple of eight bits, (one to seven) zero bits shall be appended to it to produce a multiple of eight bits.
11.1.4 In the __ALIGNED__ variant of these encoding rules, any bit-fields in the field-list shall be concatenated __without padding__, and any octet-aligned bit-fields shall be concatenated __after (zero to seven) zero bits have been concatenated__ to make the length of the encoding produced so far a multiple of eight bits. If the result of encoding the outermost value is an empty bit string, the bit string shall be replaced with a single octet with all bits set to 0. If it is a non-empty bit string and it is not a multiple of eight bits, __(zero to seven) zero bits shall be appended to it to produce a multiple of eight bits.__

And some corrections from [Rec. ITU-T X.691 (2015)/Cor.1 (10/2016)](https://www.itu.int/rec/dologin.asp?lang=e&id=T-REC-X.691-201610-I!Cor1!PDF-E&type=items)
>2
Clause 11.1.3
Modify clause 11.1.3 as follows:
11.1.3 In the __UNALIGNED variant of these encoding rules, all fields shall be concatenated without padding.__ In all the cases of 11.1.1 except case b), subclause 11.1.3.1 applies. In case b) of 11.1.1, subclause 11.1.3.2 applies.
11.1.3.1 (The result of the encoding is not contained in an ASN.1 bitstring) If the result of encoding the outermost valueis an empty bit string, the bit string shall be replaced with a single octet with all bits set to 0. __If it is a non-empty bit stringand it is not a multiple of eight bits, (one to seven) zero bits shall be appended to it to produce a multiple of eight bits.__
11.1.3.2 (The result of the encoding is contained in an ASN.1 bitstring) If the result of encoding the outermost value is an empty bit string, the bit string shall be replaced with a single bit set to 0. __No padding bits shall be appended.__

**Comment by mouse07410** [comment]
Thanks!
