### ISSUE TITLE
Encoding large numbers in Object Identifiers

### ISSUE THREAD

**Issue by Luis-Abreu** [vlm/asn1c#261]
Hi! 
I'm trying to encode the following OID using ASN1C:
"1.2.3.1.1.1.21777.3.5.1.1"
Since OIDs are encoded into uint8_t arrays that means that each OID node must be smaller than 127. (8 bits per node).

Any ideas if it is possible to do this using this library?
Thank you for your work on this project! 👍

**Comment by velichkov** [comment]
Hi @Luis-Abreu,

> Since OIDs are encoded into uint8_t arrays that means that each OID node must be smaller than 127. (8 bits per node).
Any ideas if it is possible to do this using this library?

Yes it should be, have a look how the decode is done in the tests, the encode must be similar.

https://github.com/vlm/asn1c/blob/4cc779fd9bd7f556699b5863cf111b359da10b66/tests/tests-skeletons/check-OIDs.c#L16-L62

https://github.com/vlm/asn1c/blob/4cc779fd9bd7f556699b5863cf111b359da10b66/tests/tests-skeletons/check-OIDs.c#L244-L250

And here is a patch that test decode of your OID

```patch
diff --git a/tests/tests-skeletons/check-OIDs.c b/tests/tests-skeletons/check-OIDs.c
index eb0a0147..bdd47871 100644
--- a/tests/tests-skeletons/check-OIDs.c
+++ b/tests/tests-skeletons/check-OIDs.c
@@ -17,7 +17,7 @@ static void
 check_OID(int lineno, uint8_t *buf, size_t len, unsigned *ck_buf, int ck_len) {
     OBJECT_IDENTIFIER_t *oid;
     asn_dec_rval_t rval;
-    uint32_t arcs[10];
+    uint32_t arcs[11];
     int alen;
     int i;
 
@@ -265,6 +265,14 @@ check_binary_parsing() {
     };
     uint32_t buf5_check[] = { 2, 2, 1, 0, 1 };
 
+    /* {joint-iso-itu-t 25957 } */
+    uint8_t buf6[] = {
+        0x06,   /* OBJECT IDENTIFIER */
+        0x0c,   /* Length */
+        0x2a, 0x03, 0x01, 0x01, 0x01, 0x81, 0xaa, 0x11, 0x03, 0x05, 0x01, 0x01
+    };
+    uint32_t buf6_check[] = { 1, 2, 3, 1, 1, 1, 21777, 3, 5, 1, 1 };
+
     /* {0 0} */
     uint8_t buf10[] = {
         0x0D,   /* RELATIVE-OID */
@@ -295,6 +303,7 @@ check_binary_parsing() {
     CHECK_OID(3);
     CHECK_OID(4);
     CHECK_OID(5);
+    CHECK_OID(6);
 
     CHECK_ROID(10);
     CHECK_ROID(11);
```

**Comment by mouse07410** [comment]
Since OID elements can be pretty large, and I've seen several cases where they're as big as `uint32_t` (e.g., MIB that uses IPv4 address represented as an unsigned integer as one of the indices) - I think asn1c needs to change its practice of using `uint8_t` for OID encoding, and move to something at least as big as `uint32_t`. 

@velichkov, @vlm - what do you think?

**Comment by velichkov** [comment]
Hi @mouse07410,

>Since OID elements can be pretty large, and I've seen several cases where they're as big as uint32_t (e.g., MIB that uses IPv4 address represented as an unsigned integer as one of the indices) - I think asn1c needs to change its practice of using uint8_t for OID encoding, and move to something at least as big as uint32_t.

In the API for OID elements (arcs) the `asn_oid_arc_t` type is used which currently is `uint32_t`

https://github.com/vlm/asn1c/blob/4cc779fd9bd7f556699b5863cf111b359da10b66/skeletons/OBJECT_IDENTIFIER.h#L16-L17

https://github.com/vlm/asn1c/blob/4cc779fd9bd7f556699b5863cf111b359da10b66/skeletons/OBJECT_IDENTIFIER.h#L82-L83

https://github.com/vlm/asn1c/blob/4cc779fd9bd7f556699b5863cf111b359da10b66/skeletons/OBJECT_IDENTIFIER.h#L95-L96

As you could see in the patch from my previous message 21777 is encoded in 3 bytes

 > 0x2a, 0x03, 0x01, 0x01, 0x01, **0x81, 0xaa, 0x11**, 0x03, 0x05, 0x01, 0x01

and the whole OID is encoded in 11 bytes so I don't see any reason to change the result buffer type.

**Comment by mouse07410** [comment]
@velichkov yes your additional test passes fine, thanks.

I'll play with OID encoding a bit more, but you're probably right anyway.

**Comment by Luis-Abreu** [comment]
Yes, you're right @velichkov . I didn't realize there was a _OBJECT_IDENTIFIER_set_arcs()_ function. Everything is working fine now, just have one more issue but it's probably best to open a new thread.

Thank you! 👍
