### ISSUE TITLE
Missing EOC tags when encoding

### ISSUE THREAD

**Issue by Luis-Abreu** [vlm/asn1c#262]
Hello,
I've noticed that when I use openssl's asn1parse tool to dump a BER that was encoded using this library, I don't see any EOC tags.
I'm interfacing with a server that uses BouncyCastle to decode the BERs that I send to it. At the moment the server is giving me an error and I was wondering if the lack of EOC tags makes any difference or if the problem is elsewhere.
Any ideas?

Thanks again!

**Comment by velichkov** [comment]
Hi @Luis-Abreu,

The reason there is no EOC (end-of-contents) octets is that the `asn1c` uses DER encoding which is subset of BER and in DER the indefinite form is not used 

From ITU-T Rec. X.690
> 10 Distinguished encoding rules
The encoding of a data values employed by the distinguished encoding rules is the basic encoding described in clause 8, together with the following restrictions and those also listed in clause 11.
10.1 Length forms
The definite form of length encoding shall be used, encoded in the minimum number of octets. [Contrast
with 8.1.3.2 b).]

https://github.com/vlm/asn1c/blob/4cc779fd9bd7f556699b5863cf111b359da10b66/skeletons/asn_application.c#L268-L285

**Comment by Luis-Abreu** [comment]
Hi @velichkov,
The server I'm interacting with is running BouncyCastle and is expecting a BER, not a DER. Is there anyway to encode in BER using this library?
At this point, the only difference between the DER's i'm generating and the BERS i'm supposed to send is in the length of each element. The "correct" BER's have indefinite length while mine are definitive.
Thanks again for your help!

**Comment by Luis-Abreu** [comment]
To further clarify,
The DER I'm generating using this library starts with a sequence of definitive length. When I send this DER to the server it parses it as a DLSequence (which in BouncyCastle, is nothing more than a Sequence of definitive lenght). The problem is, I need it to be a BERSequence (which means a Sequence of indefinitive lenght). 
Any way of changing every definitive length element into indefinitive ones?

Thank you!

**Comment by velichkov** [comment]
Hi @Luis-Abreu,

> The server I'm interacting with is running BouncyCastle

Maybe it's time to report this issue to the BouncyCastle or to whoever has implemented your server.

>  and is expecting a BER, not a DER.  Is there anyway to encode in BER using this library?

As I stated previously DER is a subset of BER so every valid DER message is a valid BER message. If this server supports BER and your message is a valid DER message then the server have to be able to decode it. If it can't decode it then it does not support BER.

> At this point, the only difference between the DER's i'm generating and the BERS i'm supposed to send is in the length of each element. The "correct" BER's have indefinite length while mine are definitive.

There is another variant of BER called Canonical Encoding Rules (CER). The key difference between the two is that DER always uses the definite length form of encoding while CER always uses the indefinite length form. See [Rec. ITU-T X.690 (08/2015)"](https://www.itu.int/rec/dologin_pub.asp?lang=e&id=T-REC-X.690-201508-I!!PDF-E&type=items) " paragraphs 9, 10 and 11.
 
And no, CER is currently not supported in `asn1c`

>  Any way of changing every definitive length element into indefinitive ones?

No easy way as far as I know. You could try use the `*_encode_der` functions as a base and implement the `CER` encoding.

P.S
Please close the other issues if you have no more questions there.

**Comment by mouse07410** [comment]
> Maybe it's time to report this issue to the BouncyCastle or to whoever has implemented your server.

I'm fairly close to the BouncyCastle team, and can pick up this direction investigating this problem. But my bet would be that the server is doing something wrong.

More details on exactly what class/method of BouncyCastle is invoked, by what code, and with what parameters would help.

I don't think BC supports CER, but I never bothered to check (still, since BC is a crypto package, I'd expect a fairly competent support of DER as all the certs are DER-encoded, but not CER).

**Comment by Luis-Abreu** [comment]
> But my bet would be that the server is doing something wrong.
After finally being granted access to the server's code and I can see that indeed the problem is in the server. The parsing on the server's side is forcing every element to be BER related, instead of DER. And everything that isn't a BERSequence or a BERApplicationSpecific is being thrown out, and that's whats causing the problem. I've changed it to allow both BER and DER and for now it is doing the job.

In the end, BouncyCastle allows the users to do whatever they want and do not follow the "Be liberal in what you accept and conservative in what you send" rule, which opens up the possibility to making mistakes like this one.

Anyways, couldn't have done it without you guys help, so thank you again!

**Comment by mouse07410** [comment]
> The parsing on the server's side is forcing every element to be BER related, instead of DER. And everything that isn't a BERSequence or a BERApplicationSpecific is being thrown out, and that's whats causing the problem. I've changed it to allow both BER and DER and for now it is doing the job.

Glad you found (and fixed) the problem, and it's working for you now.

> In the end, BouncyCastle allows the users to do whatever they want 

Which is great, because different people have different needs.

> and do not follow the "Be liberal in what you accept and conservative in what you send" rule, 

I'd like to hear more on where exactly BC doesn't follow it. In your example, if the server tells BC to not accept something, how is it BC's fault or oversight? 

Although, I might bring this up with the BC team to hear what they think about this issue.

> which opens up the possibility to making mistakes like this one.

IMHO, it is infeasible to create a usable library that prevents every possible foolish mistake on behalf of the caller.  ;-)

**Comment by Luis-Abreu** [comment]
> IMHO, it is infeasible to create a usable library that prevents every possible foolish mistake on behalf of the caller. ;-)
A good example of what I meant by that is the fact that in BC, the datatype "BERApplicationSpecific" inherits from "DERApplicationSpecific". IMO that breaks a fundamental principle of ASN.1 that @velichkov mentioned above, that every DER is a valid BER, but not every BER is a valid DER. 
Sure it's impossible to create a library that prevents every possible misuse but there are always core principles that should be protected

**Comment by mouse07410** [comment]
> ...in BC, the datatype "BERApplicationSpecific" inherits from "DERApplicationSpecific". IMO that breaks a fundamental principle of ASN.1 that @velichkov mentioned above, that every DER is a valid BER, but not every BER is a valid DER.

You are right - this should be addressed. I'll talk to them.

**Comment by mouse07410** [comment]
@Luis-Abreu I forgot to ask: what version of BouncyCastle does your server use? And it would be great if you could 
- post a (short?) sample of the code that fails to parse the correct DER
- post the fix
- post a short sample (say, hex-encoded) DER_encoded data that can demonstrate this problem

It would help fixing BC (assuming the team is convinced it's a problem).

**Comment by mouse07410** [comment]
Also, here's the recommendation I got so far:

> The code should have been written using `ASN1Sequence.getInstance()`. ASN.1 streams, as objects, can contain both primitive and user defined types - casting in that situation will only cause errors, errors which will often hide during development and show up as unexpected side effects resulting from apparently trivial changes. Don't cast, use the `.getInstance()` methods, that's what they are for.

**Comment by mouse07410** [comment]
@Luis-Abreu are you interested in a change in BC? If so, please post the info I requested. Otherwise I'll assume that you're happy with your workaround, and with the answer I passed along from the BC team  - and no more effort is needed on this.
