### ISSUE TITLE
J2735 shared object library

### ISSUE THREAD

**Issue by josephquzhou** [vlm/asn1c#286]
Hi,

By using the Makefile in /examples/sample.source.J2735 I can get a libasncodec.a (static) library. Is there a way I can get a shared object library (.so)?

Thanks!

Joseph

**Comment by brchiu** [comment]
@josephquzhou , there are static variables used in several places of skeleton files, e.g. #283, and function `asn_bit_data_string()` of `asn_bit_data.c`. So be cautioned that the built library might not be thread-safe. Also the generated C files shall be checked for it.

Of course if you use your built shared object library (.so) only within a single thread application. Thread-safety perhaps can be compromised.


If the aforementioned issues are not your concern, then : 

1. Add `-fPIC` to `CFLAGS` of `Makefile`.
2. Add one line below `$(AR) .....` of `converter-example.mk`.
```
$(ASN_LIBRARY): $(ASN_MODULE_SRCS:.c=.o)
	$(AR) rcs $@ $(ASN_MODULE_SRCS:.c=.o)
	$(CC) -shared -o $(ASN_LIBRARY:.a=.so) $@ $(ASN_MODULE_SRCS:.c=.o)
```

**Comment by josephquzhou** [comment]
@brchiu, 
After I did the two changes you recommended, the libasncodec.so was successfully generated. However the .so library couldn't be used for compiling. Is there anything else I should do? 

Thanks!
Joseph

**Comment by brchiu** [comment]
I am not sure your `"the .so library couldn't be used for compiling"` means. 

I assume it is a result that compiler is not aware where this `.so` is.

If it is indeed the case, you can add `-L<directory name>` in your command line to instruct gcc adding library search path and add `-l<library name without lib and .so>` to instruct gcc this dynamic library name.
 
`gcc -L/home/username/foo -Wall -o test main.c -lfoo`

All these information can be easily found by searching internet using proper keywords which already exist in your questions. For example, the following link found : 

https://www.cprogramming.com/tutorial/shared-libraries-linux-gcc.html

**Comment by vlm** [comment]
Thank you, @brchiu !
