### ISSUE TITLE
How to use Choice and Enum Types

### ISSUE THREAD

**Issue by momor10** [vlm/asn1c#302]
Im trying to build a structure with asn1c and encode it with uper to send it through udp to a server using c++/qt. The .c and .h files are generated using the windows version 0.9.21 of asn1c. (the online version does not load saying: User playground initialization failed.
Windows installer: asn1c-0.9.21.exe (2006-Sep-26) 2.2 MB. 
 
The process is crashing when trying to build the structure that contains a "choice" with the following error:
Exception at 0x2b0982, code: 0xc0000005: write access violation at: 0x0, flags=0x0 (first chance)

The relevant asn1 part:
```
CamParameters::= SEQUENCE {
    basicContainer BasicContainer,
    highFrequencyContainer HighFrequencyContainer,
    lowFrequencyContainer LowFrequencyContainer OPTIONAL,
    specialVehicleContainer SpecialVehicleContainer OPTIONAL,
    ...
}

HighFrequencyContainer::= CHOICE {
    basicVehicleContainerHighFrequency BasicVehicleContainerHighFrequency,
    rsuContainerHighFrequency RSUContainerHighFrequency,
    ...}
```

the relevant code:
```
ProtectedCommunicationZone *list = static_cast<ProtectedCommunicationZone *>(calloc(1, sizeof(ProtectedCommunicationZone)));
    c->cam.camParameters.highFrequencyContainer.choice.rsuContainerHighFrequency.protectedCommunicationZonesRSU->list.array = &list;
    c->cam.camParameters.highFrequencyContainer.choice.rsuContainerHighFrequency.protectedCommunicationZonesRSU->list.count = 0;
    c->cam.camParameters.highFrequencyContainer.choice.rsuContainerHighFrequency.protectedCommunicationZonesRSU->list.free = 0;
    c->cam.camParameters.highFrequencyContainer.choice.rsuContainerHighFrequency.protectedCommunicationZonesRSU->list.size = sizeof(ProtectedCommunicationZone);
    int ret = asn_check_constraints(&asn_DEF_Cam, c, errbuf, &errlen);
    if (ret) {
        qDebug() << "Constraintvalidationfailed: " << errbuf;
    }
    asn_enc_rval_s result = uper_encode_to_buffer(&asn_DEF_Cam, c, buf, MAX_UPER_BUFFER_SIZE);
    if (result.encoded == -1) {
        qDebug() << "Error Encoding: " << result.failed_type->name;
    } else {
        qDebug() << result.encoded << " Bytes encoded";
        QByteArray datagram = QByteArray((char *)buf, result.encoded);
        udpSocket->writeDatagram(datagram, QHostAddress(mIP), mPort);
    }
```

One more question: How do i use the enum types?
Here altidudeConfidence is type ASN__PRIMITIVE_TYPE_s with a buf/size variable. The comments state that it should never be used directly. However using the enum will not work due to different types:
`    c->cam.camParameters.basicContainer.referencePosition.altitude.altitudeConfidence = AltitudeConfidence_unavailable;`

**Comment by momor10** [comment]
thx for your answer.
im not sure where to start, do you have some kind of example code for both cases? calloc should initiialize the pointer? i tried using malloc with the same result.

**Comment by DavidKelleySCSC** [comment]
I will look about for some old examples, as I know they exist.  It may be Monday to dig it out, FYI these days in our shop we use Qt for everything.  But part of the below may be helpful to you.   The root issue is not allocating the space but that the internal pointers in the structure of that space also must be allocated and/or set.  

For myself, much of that early work was done (in .net) around 2010 when DSRC messages were in in BER (they are in UPER now).  At the time myself and others wrote an early guide that was mostly ASN BER educational in nature. The was done with FHWA sponsorship and published by SAE.org but I cannot seem to find a current link to it. Unlike the actual stds, this was outreach material and was free to download from SAE and FHWA and others.  The formal title is "DSRC Implementation Guide - A guide to users of SAE J2735 message sets over DSRC" and I see a number of site are hosting copies, try a web search. Here are two, http://one-its-webapp1.transport.utoronto.ca/c/document_library/get_file?p_l_id=46711&folderId=52909&name=DLFE-1001.pdf   and  https://www.yumpu.com/en/document/view/25934070/dsrc-implementation-guide-sae

In that document the issues of using the asn1c tools are well covered as that was the tool used to construct the code examples.  Today I would not approach the problem that way, but the core use of common constructors to address the initialization and dangling ptr issues would be the same.

**Comment by momor10** [comment]
thank you. i used the newest sourcecode to compile the asn1c compiler and generate the c and h files with it. it uses native types by default. So now this is possible:
```
    cam_p->header.stationID = 1;
    cam_p->cam.camParameters.basicContainer.referencePosition.altitude.altitudeConfidence = AltitudeConfidence_unavailable;
```
