### ISSUE TITLE
Accessing individual members of a SEQUENCE_OF

### ISSUE THREAD

**Issue by ManlyCoding** [vlm/asn1c#304]
I'm having trouble understanding how to access elements of a SEQUENCE_OF.

Lets imagine that I have a "SequenceOfCertificate_t" defined as:

```
#ifndef	_SequenceOfCertificate_H_
#define	_SequenceOfCertificate_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Certificate;

/* SequenceOfCertificate */
typedef struct SequenceOfCertificate {
	A_SEQUENCE_OF(struct Certificate) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SequenceOfCertificate_t;
```

Then, a SEQUENCE_OF, that is a redefinition of A_SET_OF, defined as:

```
#ifndef	ASN_SET_OF_H
#define	ASN_SET_OF_H

#ifdef __cplusplus
#define A_SET_OF(type)                   \
    struct {                             \
        type **array;                    \
        int count; /* Meaningful size */ \
        int size;  /* Allocated size */  \
        void (*free)(decltype(*array));  \
    }
#else   /* C */
#define A_SET_OF(type)                   \
    struct {                             \
        type **array;                    \
        int count; /* Meaningful size */ \
        int size;  /* Allocated size */  \
        void (*free)(type *);    \
    }
#endif

#ifdef __cplusplus
extern "C" {
#284 
```

I fail to grasp how to recover individual *Certificate_t* of the sequence to check the values inside, since I can only access `list.array` which I suppose its the head of a list?

Thanks a lot for your help.

**Comment by velichkov** [comment]
Hi @ManlyCoding,

> since I can only access list.array which I suppose its the head of a list?

Yes this is the head of the list. Here is an example from the test suite

https://github.com/vlm/asn1c/blob/4cc779fd9bd7f556699b5863cf111b359da10b66/tests/tests-c-compiler/check-src/check-31.-fwide-types.c#L108-L125

**Comment by ManlyCoding** [comment]
> Hi @ManlyCoding,
> 
> > since I can only access list.array which I suppose its the head of a list?
> 
> Yes this is the head of the list. Here is an example from the test suite
> 
> [asn1c/tests/tests-c-compiler/check-src/check-31.-fwide-types.c](https://github.com/vlm/asn1c/blob/4cc779fd9bd7f556699b5863cf111b359da10b66/tests/tests-c-compiler/check-src/check-31.-fwide-types.c#L108-L125)
> 
> Lines 108 to 125 in [4cc779f](/vlm/asn1c/commit/4cc779fd9bd7f556699b5863cf111b359da10b66)
>  if(is_ok) { 
>  	assert(rval.code == RC_OK); 
>  	assert(rval.consumed == consumed); 
>   
>  	assert(t.list.count == 2); 
>  	assert(t.list.array[0]->height.size == 1); 
>  	assert(t.list.array[0]->width.size == 1); 
>  	assert(t.list.array[1]->height.size == 1); 
>  	assert(t.list.array[1]->width.size == 1); 
>  } else { 
>  	if(rval.code == RC_OK) { 
>  		assert(t.list.count != 2 
>  		|| t.list.array[0]->height.size != 1 
>  		|| t.list.array[0]->width.size != 1 
>  		|| t.list.array[1]->height.size != 1 
>  		|| t.list.array[1]->width.size != 1 
>  		); 
>  	}

Correct me if I am wrong, but does that mean I can simply access the members as if they were in an array? Even if they have different sizes? And do the members retain their type or do I have to cast them back to a Certificate_t?

**Comment by velichkov** [comment]
> but does that mean I can simply access the members as if they were in an array?

Yes as seen in the example above.

> Even if they have different sizes?

The sizeof of the struct (`Certificate_t` in your case) is always the same for all elements.

> And do the members retain their type or do I have to cast them back to a Certificate_t?

You don't have to cast them as seen in the above example.

**Comment by ManlyCoding** [comment]
> > but does that mean I can simply access the members as if they were in an array?
> 
> Yes as seen in the example above.
> 
> > Even if they have different sizes?
> 
> The sizeof of the struct (`Certificate_t` in your case) is always the same for all elements.
> 
> > And do the members retain their type or do I have to cast them back to a Certificate_t?
> 
> You don't have to cast them as seen in the above example.

Thanks a lot @velichkov I'm a novice in C so I'm struggling. You are a life saver!

**Comment by velichkov** [comment]
> Thanks a lot @velichkov I'm a novice in C so I'm struggling. You are a life saver!

No problem. Don't forget to close this issue once you write and test your program successfully.
