### ISSUE TITLE
Error uper encoding & decoding Latitude and Longitude

### ISSUE THREAD

**Issue by Mowuannals** [vlm/asn1c#305]
I met a strange problem.
The DataFrame Position3D is defined as follow:

> DefPosition DEFINITIONS AUTOMATIC TAGS ::= BEGIN
> Position3D ::= SEQUENCE {
> 		lat Latitude, 
> 		-- in 1/10th micro degrees
> 		long Longitude, 
> 		-- in 1/10th micro degrees
> 		elevation Elevation OPTIONAL
> 		-- in 10 cm units
> 	}
>         Latitude ::= INTEGER (-900000000..900000001) 
> 	-- LSB = 1/10 micro degree 
> 	-- Providing a range of plus-minus 90 degrees
> 	
> 	Longitude ::= INTEGER (-1800000000..1800000001) 
> 	-- LSB = 1/10 micro degree 
> 	-- Providing a range of plus-minus 180 degrees
> 	
> 	Elevation ::= INTEGER (0..61439)
> 	-- In units of 10 cm steps above or below the reference ellipsoid
> 	-- Providing a range of -409.5 to + 6143.9 meters
> 	-- The value -4096 shall be used when Unknown is to be sent
> END
> 

After setting the value of Longitude and Latitude, I use the function uper_encode to transfer the information into uper-encoded buffer. The er.encoded told me the function successfully processed, but I failed to achieve the correct value of  longitude and latitude when I use the function uper_decode. The following is the detailed code:

> static int decode_callback(const void *buffer, size_t size, void *app_key)
> {
> 	static int i = 0;
> 	memcpy(&message[i], buffer, size);
> 	i += size;
> 	return 0;
> }
> void main()
> {
> 	Position3D_t *mypos;
> 	mypos = (Position3D_t *)calloc(1, sizeof(*mypos));
> 	mypos->lat = 123000000;
> 	mypos->Long = 144000000;
> 	asn_enc_rval_t er;
> 	er = uper_encode(&asn_DEF_Position3D, mypos, decode_callback, message);
> 	xer_fprint(stdout, &asn_DEF_Position3D, mypos);
> 	Position3D_t *mypos1;
> 	mypos1 = (Position3D_t *)calloc(1, sizeof(*mypos1));
> 	asn_dec_rval_t ec;
> 	ec = uper_decode(0, &asn_DEF_Position3D, (void **)&mypos1, message, sizeof(message), 0, 0);
> 	xer_fprint(stdout, &asn_DEF_Position3D, mypos1);
> 	return;
> }
> 

And the xml-print screenshot is also shown as follow:

![1542789532 1](https://user-images.githubusercontent.com/45225263/48828940-04790d00-edac-11e8-9e54-0a548cbfd956.png)

 I feel so strange  because when I use the function der_encode and ber_decode,the encoded buffer and decoded value is correct only if I use the uper rule the problem exists.

**Comment by velichkov** [comment]
Hi @Mowuannals

> er = uper_encode(&asn_DEF_Position3D, mypos, decode_callback, message);

This does not compile with the latest asn1c from the master branch(4cc779fd9bd7f556699b5863cf111b359da10b66)
The gcc fails with
```
test.c:22:7: error: too few arguments to function ‘uper_encode’
  er = uper_encode(&asn_DEF_Position3D, mypos, decode_callback, message);
       ^~~~~~~~~~~
In file included from ./constr_TYPE.h:42,
                 from ./asn_application.h:167,
                 from Position3D.h:12,
                 from test.c:4:
./per_encoder.h:23:16: note: declared here
 asn_enc_rval_t uper_encode(
                ^~~~~~~~~~~
```
and few more warnings before it

I'm able to successfully encode/decode your structure using the converter-example from the latest master branch. Here is the commands I've used to test it.

```
$ asn1c -pdu=Position3D -pdu=all -gen-PER defposition.asn1
$ make -f converter-example.mk
$ ./converter-example -ixer message.xer -oper > message.uper
$ cat message.xer 
<Position3D>
	<lat>123000000</lat>
	<long>144000000</long>
</Position3D>
$ ./converter-example -ixer message.xer -oper > message.uper
$ xxd message.uper 
00000000: 3cf9 bdc0 73df 1600                      <...s...
$ ./converter-example -iper message.uper 
<Position3D>
    <lat>123000000</lat>
    <long>144000000</long>
</Position3D>
```

So my advice is to try with the latest master using the above commands and if it still fails provide some more information like the OS version, compiler version, 32 or 64bits, etc...

> And the xml-print screenshot is also shown as follow:

Please never upload screenshots of text, you could copy-paste the text from the terminal.

**Comment by Mowuannals** [comment]
Thanks a lot, @velichkov 
When I use the latest asn1c compiler, the problem has been solved. Your suggestion is so helpful to me. And I will never upload screenshots,too
