### ISSUE TITLE
Problem with Time64 (uint64_t) & "struct ASN__PRIMITIVE_TYPE_s"

### ISSUE THREAD

**Issue by ManlyCoding** [vlm/asn1c#306]
I have two types, Time64 and Time32 defined in ASN1 as:

```
-- ------------------------------------------------------------------
--
-- Integers
--
-- ------------------------------------------------------------------
Uint3 ::= INTEGER (0..7) -- (hex) 07
Uint8 ::= INTEGER (0..255) -- (hex) ff
Uint16 ::= INTEGER (0..65535) -- (hex) ff ff
Uint32 ::= INTEGER (0..4294967295)--<LONGLONG>-- -- (hex) ff ff ff ff
Uint64 ::= INTEGER (0..18446744073709551615) -- (hex) ff ff ff ff ff ff ff ff
SequenceOfUint8 ::= SEQUENCE OF Uint8
SequenceOfUint16 ::= SEQUENCE OF Uint16
-- ------------------------------------------------------------------
--
-- Time
--
-- ------------------------------------------------------------------
Time32 ::= Uint32
Time64 ::= Uint64
ValidityPeriod ::= SEQUENCE {
start Time32,
duration Duration
}
Duration ::= CHOICE {
microseconds Uint16,
milliseconds Uint16,
seconds Uint16,
minutes Uint16,
hours Uint16,
sixtyHours Uint16,
years Uint16
}
```

This ASN1 compiles flawlessly into these .c and .h headers:

_*Time32.h:*_
```
#ifndef	_Time32_H_
#define	_Time32_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Uint32.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Time32 */
typedef Uint32_t	 Time32_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Time32_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Time32;
asn_struct_free_f Time32_free;
asn_struct_print_f Time32_print;
asn_constr_check_f Time32_constraint;
ber_type_decoder_f Time32_decode_ber;
der_type_encoder_f Time32_encode_der;
xer_type_decoder_f Time32_decode_xer;
xer_type_encoder_f Time32_encode_xer;
oer_type_decoder_f Time32_decode_oer;
oer_type_encoder_f Time32_encode_oer;
per_type_decoder_f Time32_decode_uper;
per_type_encoder_f Time32_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Time32_H_ */
#include <asn_internal.h>
```
and _*Time64.h*_:

```
#ifndef	_Time64_H_
#define	_Time64_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Uint64.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Time64 */
typedef Uint64_t	 Time64_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Time64_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Time64;
asn_struct_free_f Time64_free;
asn_struct_print_f Time64_print;
asn_constr_check_f Time64_constraint;
ber_type_decoder_f Time64_decode_ber;
der_type_encoder_f Time64_encode_der;
xer_type_decoder_f Time64_decode_xer;
xer_type_encoder_f Time64_encode_xer;
oer_type_decoder_f Time64_decode_oer;
oer_type_encoder_f Time64_encode_oer;
per_type_decoder_f Time64_decode_uper;
per_type_encoder_f Time64_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Time64_H_ */
#include <asn_internal.h>
```
However, when compiling the main program, if I have to make a comparation or any arithmetic operation that involves _Time64_, I get the following error:

```
 invalid operands to binary >= (have ‘Time64_t’ {aka ‘struct ASN__PRIMITIVE_TYPE_s’} and ‘Time32_t’ {aka ‘long unsigned int’})
```
For some reason, Time32 gets properly translated into an scalar type, while Time64 isn't and therefore I cant operate with any Time64 value.
Any idea about why Time64 is not being translated into an uint64_t?

Thanks in advance.

**Comment by ManlyCoding** [comment]
I managed to solve the problem myself, I was mixing *uint64_t* and *Uint64_t" which are not the same thing. Also, Uint64_t should be translated to an int64 to have the proper size, but that would be signed, so the asn1c compiler transforms the Uint64_t into an *struct ASN__PRIMITIVE_TYPE_s" defined inside asn_codecs_prim as:
```
typedef struct ASN__PRIMITIVE_TYPE_s {
    uint8_t *buf;   /* Buffer with consecutive primitive encoding bytes */
    size_t size;    /* Size of the buffer */
} ASN__PRIMITIVE_TYPE_t;
```
That I can now typecast to an uint64_t to operate. However, that sound like a very dirty solution as I would have to transform an uint64_t into a uint8_t buffer whenever I wanted to initialize a TIme64. Is that correct?

**Comment by velichkov** [comment]
Hi @ManlyCoding,

>while Time64 isn't and therefore I cant operate with any Time64 value.
>Any idea about why Time64 is not being translated into an uint64_t?

For an explanation why see

https://github.com/vlm/asn1c/blob/4cc779fd9bd7f556699b5863cf111b359da10b66/libasn1compiler/asn1c_misc.c#L379-L389

Also you could force the `asn1c` compiler to always use `INTEGER_t`/`ASN__PRIMITIVE_TYPE_t` with the following option
```
 -fwide-types          Use INTEGER_t instead of "long" by default, etc.
```
> That I can now typecast to an uint64_t to operate. However, that sound like a very dirty solution as I would have to transform an uint64_t into a uint8_t buffer whenever I wanted to initialize a TIme64

Better use the conversion functions as a typecast is not enough

https://github.com/vlm/asn1c/blob/4cc779fd9bd7f556699b5863cf111b359da10b66/skeletons/INTEGER.h#L56-L75

**Comment by ManlyCoding** [comment]
> Hi @ManlyCoding,
> 
> > while Time64 isn't and therefore I cant operate with any Time64 value.
> > Any idea about why Time64 is not being translated into an uint64_t?
> 
> For an explanation why see
> 
> [asn1c/libasn1compiler/asn1c_misc.c](https://github.com/vlm/asn1c/blob/4cc779fd9bd7f556699b5863cf111b359da10b66/libasn1compiler/asn1c_misc.c#L379-L389)
> 
> Lines 379 to 389 in [4cc779f](/vlm/asn1c/commit/4cc779fd9bd7f556699b5863cf111b359da10b66)
>  /* 
>   * Since we don't know the sizeof(long) on the possible target platform 
>   * which will be compiling the code generated by asn1c, let's play it 
>   * simple: long's range is equal to or greater than int32_t. 
>   * NOTE: the most negative integer cannot be written in C, as the C99 
>   * standard will give it an unsigned type. 
>   * It is defined here as a constant expression. 
>   */ 
>  #define	RIGHTMAX	2147483647	/* of 32-bit integer type */ 
>  #define	LEFTMIN		(-RIGHTMAX-1)	/* of 32-bit integer type */ 
>   
> 
> Also you could force the `asn1c` compiler to always use `INTEGER_t`/`ASN__PRIMITIVE_TYPE_t` with the following option
> 
> ```
>  -fwide-types          Use INTEGER_t instead of "long" by default, etc.
> ```
> 
> > That I can now typecast to an uint64_t to operate. However, that sound like a very dirty solution as I would have to transform an uint64_t into a uint8_t buffer whenever I wanted to initialize a TIme64
> 
> Better use the conversion functions as a typecast is not enough
> 
> [asn1c/skeletons/INTEGER.h](https://github.com/vlm/asn1c/blob/4cc779fd9bd7f556699b5863cf111b359da10b66/skeletons/INTEGER.h#L56-L75)
> 
> Lines 56 to 75 in [4cc779f](/vlm/asn1c/commit/4cc779fd9bd7f556699b5863cf111b359da10b66)
>  /* 
>   * Natiwe size-independent conversion of native integers to/from INTEGER. 
>   * (l_size) is in bytes. 
>   * Returns 0 if it was possible to convert, -1 otherwise. 
>   * -1/EINVAL: Mandatory argument missing 
>   * -1/ERANGE: Value encoded is out of range for long representation 
>   * -1/ENOMEM: Memory allocation failed (in asn_*2INTEGER()). 
>   */ 
>  int asn_INTEGER2imax(const INTEGER_t *i, intmax_t *l); 
>  int asn_INTEGER2umax(const INTEGER_t *i, uintmax_t *l); 
>  int asn_imax2INTEGER(INTEGER_t *i, intmax_t l); 
>  int asn_umax2INTEGER(INTEGER_t *i, uintmax_t l); 
>   
>  /* 
>   * Size-specific conversion helpers. 
>   */ 
>  int asn_INTEGER2long(const INTEGER_t *i, long *l); 
>  int asn_INTEGER2ulong(const INTEGER_t *i, unsigned long *l); 
>  int asn_long2INTEGER(INTEGER_t *i, long l); 
>  int asn_ulong2INTEGER(INTEGER_t *i, unsigned long l);

Totally missed those functions! That solves the problem, it would be great to have them in the guide.

Like last time, thanks a lot @velichkov, I hope that I can treat you to a beer some day!

**Comment by yadav9997** [comment]
Hi @ManlyCoding @velichkov,

can you please help in confirming which of the below conversion routines (from INTEGER.h) have you used for the Uint64, thanks:

Uint64 ::= INTEGER (0..18446744073709551615) -- (hex) ff ff ff ff ff ff ff ff

[asn1c/skeletons/INTEGER.h](https://github.com/vlm/asn1c/blob/4cc779fd9bd7f556699b5863cf111b359da10b66/skeletons/INTEGER.h#L56-L75)

Lines 56 to 75 in [4cc779f](https://github.com/vlm/asn1c/commit/4cc779fd9bd7f556699b5863cf111b359da10b66)
/*

Natiwe size-independent conversion of native integers to/from INTEGER.
(l_size) is in bytes.
Returns 0 if it was possible to convert, -1 otherwise.
-1/EINVAL: Mandatory argument missing
-1/ERANGE: Value encoded is out of range for long representation
-1/ENOMEM: Memory allocation failed (in asn_*2INTEGER()).
*/
int asn_INTEGER2imax(const INTEGER_t *i, intmax_t *l);
int asn_INTEGER2umax(const INTEGER_t *i, uintmax_t *l);
int asn_imax2INTEGER(INTEGER_t *i, intmax_t l);
int asn_umax2INTEGER(INTEGER_t *i, uintmax_t l);
/*

Size-specific conversion helpers.
*/
int asn_INTEGER2long(const INTEGER_t *i, long *l);
int asn_INTEGER2ulong(const INTEGER_t *i, unsigned long *l);
int asn_long2INTEGER(INTEGER_t *i, long l);
int asn_ulong2INTEGER(INTEGER_t *i, unsigned long l);

Thanks a lot, awaited for your valuable feedback
