### ISSUE TITLE
linker error 

### ISSUE THREAD

**Issue by SimonSchnurrbart** [vlm/asn1c#308]
Hi,
I'm trying to compile the example rectangle decoder of asn1c-usage.pdf
and I'm getting the following error:
`/tmp/ccVzOV1U.o:(.data.rel+0x38): Warnung: undefinierter Verweis auf »BIT_STRING_decode_oer«
/tmp/ccVzOV1U.o:(.data.rel+0x40): Warnung: undefinierter Verweis auf »BIT_STRING_encode_oer«
/tmp/ccNqSsHF.o:(.data.rel+0x38): Warnung: undefinierter Verweis auf »OCTET_STRING_decode_oer«
/tmp/ccNqSsHF.o:(.data.rel+0x40): Warnung: undefinierter Verweis auf »OCTET_STRING_encode_oer«
collect2: error: ld returned 1 exit status`

And if I define ASN_DISABLE_OER_SUPPORT before compiling I'm getting:

`constr_CHOICE_oer.c:128:1: error: conflicting types for ‘CHOICE_decode_oer’
 CHOICE_decode_oer(const asn_codec_ctx_t *opt_codec_ctx,
 ^~~~~~~~~~~~~~~~~
In file included from constr_CHOICE_oer.c:9:0:
./constr_CHOICE.h:50:20: note: previous declaration of ‘CHOICE_decode_oer’ was here
 oer_type_decoder_f CHOICE_decode_oer;
                    ^~~~~~~~~~~~~~~~~
constr_CHOICE_oer.c: In function ‘CHOICE_decode_oer’:
constr_CHOICE_oer.c:243:17: warning: implicit declaration of function ‘oer_open_type_get’ [-Wimplicit-function-declaration]
                 oer_open_type_get(opt_codec_ctx, elm->type,
                 ^~~~~~~~~~~~~~~~~
constr_CHOICE_oer.c:251:18: error: void value not ignored as it ought to be
             rval = elm->type->op->oer_decoder(
                  ^
constr_CHOICE_oer.c: At top level:
`
Any idea how to resolve that?

**Comment by brchiu** [comment]
Compile your code and generated codec code with -DASN_DISABLE_OER_SUPPORT to prevent linking with OER functions.

**Comment by SimonSchnurrbart** [comment]
Thanks for your fast reply!
If I use `cc -I. -o rdecode *.c -DASN_DISABLE_OER_SUPPORT`
I still get some errors:

`main.c:13:17: warning: character constant too long for its type
 fprintf(stderr, 'Usage: %s <file.ber>\n', av[0]);
                 ^~~~~~~~~~~~~~~~~~~~~~~~
main.c:13:17: warning: passing argument 2 of ‘fprintf’ makes pointer from integer without a cast [-Wint-conversion]
In file included from main.c:1:0:
/usr/include/stdio.h:312:12: note: expected ‘const char * restrict’ but argument is of type ‘int’
 extern int fprintf (FILE *__restrict __stream,
            ^~~~~~~
main.c:18:22: warning: multi-character character constant [-Wmultichar]
 fp = fopen(filename, 'rb');
                      ^~~~
main.c:18:22: warning: passing argument 2 of ‘fopen’ makes pointer from integer without a cast [-Wint-conversion]
In file included from main.c:1:0:
/usr/include/stdio.h:232:14: note: expected ‘const char * restrict’ but argument is of type ‘int’
 extern FILE *fopen (const char *__restrict __filename,
              ^~~~~
main.c:26:17: warning: character constant too long for its type
 fprintf(stderr, '%s: Empty or broken\n', filename);
                 ^~~~~~~~~~~~~~~~~~~~~~~
main.c:26:17: warning: passing argument 2 of ‘fprintf’ makes pointer from integer without a cast [-Wint-conversion]
In file included from main.c:1:0:
/usr/include/stdio.h:312:12: note: expected ‘const char * restrict’ but argument is of type ‘int’
 extern int fprintf (FILE *__restrict __stream,
            ^~~~~~~
main.c:31:17: warning: character constant too long for its type
 fprintf(stderr, '%s: Broken Rectangle encoding at byte %ld\n', filename,
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
main.c:31:17: warning: passing argument 2 of ‘fprintf’ makes pointer from integer without a cast [-Wint-conversion]
In file included from main.c:1:0:
/usr/include/stdio.h:312:12: note: expected ‘const char * restrict’ but argument is of type ‘int’
 extern int fprintf (FILE *__restrict __stream,
            ^~~~~~~
oer_decoder.c: In function ‘oer_decode’:
oer_decoder.c:36:9: error: void value not ignored as it ought to be
  return type_descriptor->op->oer_decoder(opt_codec_ctx, type_descriptor, 0,
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   struct_ptr, /* Pointer to the destination structure */
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   ptr, size /* Buffer and its size */
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   );
   ~      
oer_decoder.c: In function ‘oer_open_type_skip’:
oer_decoder.c:49:12: warning: implicit declaration of function ‘oer_fetch_length’; did you mean ‘ber_fetch_length’? [-Wimplicit-function-declaration]
     return oer_fetch_length(bufptr, size, &len);
            ^~~~~~~~~~~~~~~~
            ber_fetch_length
oer_decoder.c: In function ‘oer_open_type_get’:
oer_decoder.c:85:8: error: void value not ignored as it ought to be
     dr = td->op->oer_decoder(opt_codec_ctx, td, constraints, struct_ptr,
        ^
oer_encoder.c: In function ‘oer_encode’:
oer_encoder.c:19:12: error: void value not ignored as it ought to be
     return type_descriptor->op->oer_encoder(
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         type_descriptor, 0,
         ~~~~~~~~~~~~~~~~~~~
         struct_ptr, /* Pointer to the destination structure */
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         consume_bytes, app_key);
         ~~~~~~~~~~~~~~~~~~~~~~~
oer_encoder.c: In function ‘oer_encode_to_buffer’:
oer_encoder.c:68:12: error: void value not ignored as it ought to be
         ec = type_descriptor->op->oer_encoder(
            ^
oer_encoder.c: In function ‘oer_encode_primitive’:
oer_encoder.c:97:11: warning: implicit declaration of function ‘oer_serialize_length’; did you mean ‘ber_skip_length’? [-Wimplicit-function-declaration]
     ret = oer_serialize_length(st->size, cb, app_key);
           ^~~~~~~~~~~~~~~~~~~~
           ber_skip_length
oer_encoder.c: In function ‘oer_open_type_put’:
oer_encoder.c:127:8: error: void value not ignored as it ought to be
     er = td->op->oer_encoder(td, constraints, sptr, oer__count_bytes,
        ^
oer_encoder.c:135:8: error: void value not ignored as it ought to be
     er = td->op->oer_encoder(td, constraints, sptr, cb, app_key);
        ^
In file included from oer_support.c:9:0:
./oer_support.h:24:3: error: conflicting types for ‘asn_oer_constraints_t’
 } asn_oer_constraints_t;
   ^~~~~~~~~~~~~~~~~~~~~
In file included from ./asn_application.h:167:0,
                 from ./asn_internal.h:12,
                 from oer_support.c:7:
./constr_TYPE.h:49:14: note: previous declaration of ‘asn_oer_constraints_t’ was here
 typedef void asn_oer_constraints_t;
              ^~~~~~~~~~~~~~~~~~~~~
OPEN_TYPE_oer.c: In function ‘OPEN_TYPE_oer_get’:
OPEN_TYPE_oer.c:55:14: warning: implicit declaration of function ‘oer_open_type_get’ [-Wimplicit-function-declaration]
     ot_ret = oer_open_type_get(opt_codec_ctx, selected.type_descriptor, NULL,
              ^~~~~~~~~~~~~~~~~
`

**Comment by brchiu** [comment]
hi, sorry I forgot mention that you should add **-no-gen-OER** in command line option when you generate C files, i.e. asn1c -no-gen-OER .......

**Comment by SimonSchnurrbart** [comment]
Yes that solved my problem, thanks!
Just as information, I also had to add -no-gen-example as the converter-example would interfere with my main.c
