### ISSUE TITLE
Can't compile Template Type

### ISSUE THREAD

**Issue by nofadeaway** [vlm/asn1c#312]
I tried to compile the content in the 3GPP document named TS38.331.
The template  is defined in the document as:
-- TAG-SETUP-RELEASE-START

SetupRelease { ElementTypeParam } ::= CHOICE {
    release         NULL,
    setup           ElementTypeParam
}

-- TAG-SETUP-RELEASE-STOP
And the instances in the document  show as follow:
-- TAG-BWP-DOWNLINKCOMMON-START

BWP-DownlinkCommon ::=              SEQUENCE {
    genericParameters                   BWP,
    pdcch-ConfigCommon                  SetupRelease { PDCCH-ConfigCommon }                                     OPTIONAL,   -- Need M
    pdsch-ConfigCommon                  SetupRelease { PDSCH-ConfigCommon }                                     OPTIONAL,   -- Need M
    ...
}

-- TAG-BWP-DOWNLINKCOMMON-STOP

In the file,"BWP-DownlinkCommon.h",created by the asn1c compiler, the error codes as "struct 	*pdcch_ConfigCommon	/* OPTIONAL */;" were found without the structure type,"PDCCH_ConfigCommon_t". I wonder if there is something wrong in the .asn source file or I need to add some command line options when compiling the .asn file.

**Comment by brchiu** [comment]
@nofadeaway , use https://github.com/brchiu/asn1c branch velichkov_s1ap_plus_option_group and -pdu=all -findirect-choice -fcompound-names -gen-PER -no-gen-OER as command line options.

**Comment by nofadeaway** [comment]
@brchiu I sincerely appreciate your help and wish you success in work!

**Comment by nofadeaway** [comment]
@brchiu The program failed to encode the type "BIT_STRING".
typedef struct MIB {
	BIT_STRING_t	 systemFrameNumber;
	long	 subCarrierSpacingCommon;
	long	 ssb_SubcarrierOffset;
	long	 dmrs_TypeA_Position;
	PDCCH_ConfigSIB1_t	 pdcch_ConfigSIB1;
	long	 cellBarred;
	long	 intraFreqReselection;
	BIT_STRING_t	 spare;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MIB_t;

The codes I wrote to initialize the "BIT_STRING_t	 systemFrameNumber",show as follow:
"
MIB->systemFrameNumber.size = 1;
MIB->systemFrameNumber.buf = (uint8_t *)malloc(MIB->systemFrameNumber.size);
MIB->systemFrameNumber.bits_unused = 2;
*(MIB->systemFrameNumber.buf) = (system_frame_number >> 2);
"

Previously,I used the old version asn1c 0.9.28 and the encoding succeeded. Now I use the branch velichkov_s1ap_plus_option_group and the type BITSTRING,named"systemFrameNumber", can not be encoded. Could you teach me how to initialize and assign the type BITSTRING and the member with the attribute OPTIONAL,like member named q_RxLevMinOffset in SIB1.They are all pointers.I wonder how to initialize these optional members.Is that right when I choose not to include these optional members I need to set the value of these pointers to NULL?
struct SIB1__cellSelectionInfo {
		Q_RxLevMin_t	 q_RxLevMin;
		long	*q_RxLevMinOffset;	/* OPTIONAL */
		Q_RxLevMin_t	*q_RxLevMinSUL;	/* OPTIONAL */
		Q_QualMin_t	*q_QualMin;	/* OPTIONAL */
		long	*q_QualMinOffset;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *cellSelectionInfo;
