### ISSUE TITLE
Can not compile 38.413

### ISSUE THREAD

**Issue by and2000** [vlm/asn1c#316]
By compiling 3gpp TS 38.413-f10.asn, the asn1c give this error message:
ASN.1 grammar parse error near line 941 (token "id-AMF-UE-NGAP-ID"): syntax error, unexpected TOK_identifier, expecting '}'

Seems asn1c can not handle this kind of rules:
PDUSessionResourceSetupRequestIEs NGAP-PROTOCOL-IES ::= {
{ ID id-AMF-UE-NGAP-ID       CRITICALITY reject TYPE AMF-UE-NGAP-ID        PRESENCE mandatory }|
{ ID id-RAN-UE-NGAP-ID       CRITICALITY reject TYPE RAN-UE-NGAP-ID        PRESENCE mandatory }|
{ ID id-RANPagingPriority      CRITICALITY ignore TYPE RANPagingPriority       PRESENCE optional  }|
{ ID id-NAS-PDU         CRITICALITY reject TYPE NAS-PDU         PRESENCE optional  }|
{ ID id-PDUSessionResourceSetupListSUReq  CRITICALITY reject TYPE PDUSessionResourceSetupListSUReq  PRESENCE mandatory }
,
 ...
}

**Comment by and2000** [comment]
After update asn1c  to master version(0.9.29), it can be compiled now.

**Comment by and2000** [comment]
After update asn1c to master version(0.9.29), it can be compiled now.

**Comment by raoufkh** [comment]
Hello

Can you give the link to the repo from you've got the 0.9.29 please?
