### ISSUE TITLE
Minor Security Issue

### ISSUE THREAD

**Issue by EricSesterhennX41** [vlm/asn1c#318]
Hi, I would like to report a minor security related issue, what would be the correct way? Adding the details here would mean, that they are public.

**Comment by vlm** [comment]
Please send to vlm@lionet.info

**Comment by mouse07410** [comment]
@vlm and @EricSesterhennX41, please keep me informed, as I maintain a fork at https://GitHub.com/mouse07410/asn1c.git and would like to make sure security-trusted issues are addressed ASAP.

**Comment by vlm** [comment]
Added a fuzzer test (in `check_unber`), which independently rediscovered the buffer overrun in `unber`. Fixed in `master`, thank you @EricSesterhennX41 !
