### ISSUE TITLE
Current master fails check-parsing.sh

### ISSUE THREAD

**Issue by mouse07410** [vlm/asn1c#320]
MacOS Mojave 10.14.2, Xcode-10.1, current master.
```
$ git clone https://github.com/vlm/asn1c.git
. . . . .
$ autoreconf -ivf
. . . . .
$ ./configure --prefix=/opt/local
. . . . .
$ make -j4 all && make check
. . . . .
PASS: check-xxber.sh
============================================================================
Testsuite summary for asn1c 0.9.29
============================================================================
# TOTAL: 1
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
Making check in asn1c
. . . . .
make[2]: `libasn1cskeletons.la' is up to date.
make[2]: `libasn1cskeletons_c89.la' is up to date.
Making check in tests
Making check in tests-asn1c-compiler
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-parsing.sh
make[3]: Nothing to be done for `check-parsing.sh'.
/Applications/Xcode.app/Contents/Developer/usr/bin/make  check-TESTS
FAIL: check-parsing.sh
============================================================================
Testsuite summary for asn1c 0.9.29
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See tests/tests-asn1c-compiler/test-suite.log
Please report to vlm@lionet.info
```

Complete `tests/tests-asn1c-compiler/test-suite.log` is here: 
[test-suite.log.txt](https://github.com/vlm/asn1c/files/2796982/test-suite.log.txt)

@velichkov I have the same problem in my fork (that's how I discovered it ;). It would be great if we could find and fix this problem. Also, I can reproduce this problem reliably on all machines except one (can't figure what's different about it).

**Comment by mouse07410** [comment]
@velichkov and @vlm I'm getting this problem from Travis CI for MacOS: https://travis-ci.org/mouse07410/asn1c/jobs/485717873

Ir would be nice if it could be eradicated.

**Comment by velichkov** [comment]
Hi @mouse07410,

https://travis-ci.org/mouse07410/asn1c/jobs/485717873#L1255

> $ find . -name test-suite.log -exec tail -v -n +1 {} +
tail: illegal option -- v
usage: tail [-F | -f | -r] [-q] [-b # | -c # | -n #] [file ...]

It looks like on MacOS the `tail` command does not support the `-v` flag. From `man tail`
```
       -v, --verbose
              always output headers giving file names
```
A header with the file name is useful but not that important, could you remove it and retest in order to get the full content of all `test-suite.log` files.

Try with something like
```
after_failure:
  - test "$TRAVIS_OS_NAME" == "osx" && find . -name test-suite.log -exec tail -n +1 {} +
  - test "$TRAVIS_OS_NAME" == "linux" && find . -name test-suite.log -exec tail -v -n +1 {} +
```

**Comment by mouse07410** [comment]
@velichkov thank you - I've applied the fix to `.travis.yml`, and the `test-suite.log` is now printed upon the failure: https://travis-ci.org/mouse07410/asn1c/jobs/486224548 

I don't understand why it fails. This same code compiles and passes all the tests on my Mac at home, but fails on the work machines and on Travis.

**Comment by velichkov** [comment]
https://travis-ci.org/mouse07410/asn1c/jobs/486224548#L1467-L1468
> Checking ../../tests/tests-asn1c-compiler/16-constraint-OK.asn1 against ../../tests/tests-asn1c-compiler/16-constraint-OK.asn1.-EFprint-constraints
> sed: RE error: illegal byte sequence

It seems I've already solved this problem, could you apply c22ffbb06a745a7ff093a3741b6731218720c472 and test on your work machines

**Comment by mouse07410** [comment]
After applying c22ffbb, even the machine that used to work started failing. Here's the log: 
[test-suite.log.txt](https://github.com/vlm/asn1c/files/2813557/test-suite.log.txt)

**Comment by velichkov** [comment]
> After applying c22ffbb, even the machine that used to work started failing.

You didn't resolve the conflict correctly.

In 75b7467a842f069edc3d323f52e7e44902a4b2b0 you didn't need to add both LANG=C and LC_ALL=C but if it is working you could keep it as is. The ec=0 was added in 8e1d7591a so I guess it is needed.

Also it will be good to keep the code as close to the vlm's master as possible to facilitate future merging.

**Comment by mouse07410** [comment]
Thank you - your suggestions fixed this `check-parsing.sh` problem. 

> Also it will be good to keep the code as close to the vlm's master as possible to facilitate future merging.

Striving to - but not sure how. I think I'm not adding anything unnecessary (well, maybe `LANG=C LC_ALL=C` is an overkill ;). Please feel free to point me at things that in your opinion shouldn't be there.

**Comment by mouse07410** [comment]
@velichkov Your fix works on all of my machines. Thank you!

Should I remove `LANG=C`?

**Comment by mouse07410** [comment]
@velichkov please feel free to take a look at the final working `tests/tests-asn1c-compiler/check-parsing.sh` in my fork. It appears to work on all of my systems. 

Thanks!

**Comment by mouse07410** [comment]
As the tests now pass, I think I can close this issue. Thanks!
