### ISSUE TITLE
Is generated C code architecture-size safe?

### ISSUE THREAD

**Issue by ManlyCoding** [vlm/asn1c#322]
I'm facing the problem described at #174 related to compiling latest 1609.2 asn1.
Compilation seems to be possible (with warnings) in amd64 machines, however, I'm forced to run the generated C code in a x386 one. On the surface everything seems to work, but I'm a bit restless about it, so I wanted to make sure I wont have surprises on the future.

**Comment by vlm** [comment]
Yes, it's CI runs in both 32 and 64-bit modes.

**Comment by ManlyCoding** [comment]
Thanks! That's great news!
