### ISSUE TITLE
Unable to encode the CHOICE type

### ISSUE THREAD

**Issue by AliNawazish** [vlm/asn1c#329]
Hey, I am trying to encode a CHOICE type to UPER but it is always failing.
I have the following specifications:

```
ChoiceTest ::= CHOICE {
    intCode INTEGER,
    boolCode BOOLEAN
}
```

And I encode this `CHOICE` using the following C code:

```
uint8_t *buffer = (uint8_t *) malloc(sizeof *buffer);
ChoiceTest_t *test = (ChoiceTest_t*) calloc(1, sizeof *test);
test->choice.intCode = 5;
asn_per_constraints_t *constraints = NULL;

const ssize_t ec = uper_encode_to_new_buffer(&asn_DEF_S1AP_PDU,
                                                   constraints,
                                                   test,
                                                   (void **)&buffer);
```

The encoding fails and `uper_encode_to_new_buffer` returns -1. 
Kindly help me in this.

**Comment by velichkov** [comment]
Hi @AliNawazish,

> ```
> ChoiceTest ::= CHOICE {
>     intCode INTEGER,
>     boolCode BOOLEAN
> }
> ```
> 
> And I encode this `CHOICE` using the following C code:
> 
> ```
> uint8_t *buffer = (uint8_t *) malloc(sizeof *buffer);
> ChoiceTest_t *test = (ChoiceTest_t*) calloc(1, sizeof *test);
> test->choice.intCode = 5;
> asn_per_constraints_t *constraints = NULL;
> 
> const ssize_t ec = uper_encode_to_new_buffer(&asn_DEF_S1AP_PDU,
>                                                    constraints,
>                                                    test,
>                                                    (void **)&buffer);
> ```
> 
> The encoding fails and `uper_encode_to_new_buffer` returns -1.

Most probably it fails because the first argument is wrong, it should be  something like `&asn_DEF_ChoiceTest` and not `&asn_DEF_S1AP_PDU` as you are not trying to encode `S1AP_PDU`.

Also you should not allocate the `buffer` as it is an output parameter and it's allocated in `uper_encode_to_new_buffer`

**Comment by AliNawazish** [comment]
@velichkov Thanks for the reply. 

I have now changed `&asn_DEF_S1AP_PDU` to `&asn_DEF_ChoiceTest` and removed the buffer allocation before calling `uper_encode_to_new_buffer`. However, the problem still persists. 

Any help would be appreciated.

**Comment by velichkov** [comment]
Hi @AliNawazish,

Could you share the full source code, the asn.1 file and all commands that you use to compile it in order to be able to reproduce this failure?

**Comment by AliNawazish** [comment]
test.asn file:

```
Messages DEFINITIONS ::= BEGIN
    ChoiceTest ::= CHOICE {
        intCode INTEGER,
        boolCode BOOLEAN
    }
END
```

test.c file:

```
#include "compileddir/ChoiceTest.h"

int main(){
    uint8_t *buffer;

    ChoiceTest_t *test = (ChoiceTest_t*) calloc(1, sizeof *test);
    test->choice.intCode = 1;

    asn_per_constraints_t *constraints = NULL;

    const ssize_t ec = uper_encode_to_new_buffer(&asn_DEF_ChoiceTest,
                                                constraints,
                                                test,
                                                (void **)&buffer);

    printf("Buffer size: %d\n", ec);
}
```

Commands used to generate the asn1 file:

`cd compileddir`
`asn1c ../test.asn`

Command to compile the c code:

`gcc test.c -o output -Icompileddir compileddir/*.c`

**Comment by velichkov** [comment]
You need to set the `present` field to `ChoiceTest_PR_intCode`
```
test->present = ChoiceTest_PR_intCode;
test->choice.intCode = 1;
```
In order to get some debug messages recompile with `-DASN_EMIT_DEBUG=1` in `CFLAGS`
```
gcc test.c -DASN_DISABLE_OER_SUPPORT -DASN_EMIT_DEBUG=1 -o output -Icompileddir compileddir/*.c
```
```
./output 
Encoding ChoiceTest as CHOICE (compileddir/constr_CHOICE.c:932)
Encoding ChoiceTest CHOICE element 0 (compileddir/constr_CHOICE.c:950)
CHOICE member "intCode" 0 (as 1) (compileddir/constr_CHOICE.c:983)
[PER put 1 bits 1 to 0x7ffc297b09e8+0 bits] (compileddir/asn_bit_data.c:200)
[PER out 1 1/1 (t=0,o=1) 0&0=0] (compileddir/asn_bit_data.c:243)
[PER out 128/80 => 80 buf+0] (compileddir/asn_bit_data.c:274)
Encoding NativeInteger INTEGER 1 (UPER) (compileddir/NativeInteger.c:306)
[PER put 8 bits 1 to 0x7ffc297b09e8+1 bits] (compileddir/asn_bit_data.c:200)
[PER out 8 1/1 (t=1,o=9) 80&80=80] (compileddir/asn_bit_data.c:243)
[PER out 128/80 => 80 buf+0] (compileddir/asn_bit_data.c:274)
[PER put 8 bits 1 to 0x7ffc297b09e8+9 bits] (compileddir/asn_bit_data.c:200)
[PER out 8 1/1 (t=1,o=9) 80&80=80] (compileddir/asn_bit_data.c:243)
[PER out 128/80 => 80 buf+1] (compileddir/asn_bit_data.c:274)
Freeing INTEGER as a primitive type (compileddir/asn_codecs_prim.c:125)
Complete encoded in 17 bits (compileddir/per_encoder.c:139)
Buffer size: 3
```

**Comment by AliNawazish** [comment]
@velichkov It works now. Really appreciate your help.
