### ISSUE TITLE
UPER decode is not in line with expectations

### ISSUE THREAD

**Issue by Xjianjian** [vlm/asn1c#333]
//my  .asn file
...
CfgReadReqInfo ::= SEQUENCE -- 
{
	settingIds	SEQUENCE(SIZE(1..255)) OF SettingID -- 
}
SettingID ::= SEQUENCE
{
	id 		INTEGER(0..65535) -- 
}
...

//encode
    ......
    CfgReadReqInfo_t CfgReadReq;
    memset(&CfgReadReq,0 , sizeof(CfgReadReqInfo_t));
    struct SettingID  SetID[255];
    struct SettingID *SetID_ptr = SetID;
    SetID[0].id = 2;
    SetID[1].id = 2;
    SetID[2].id = 3;
   CfgReadReq.settingIds.list.array = &SetID_ptr;
   CfgReadReq.settingIds.list.count = 1;
   CfgReadReq.settingIds.list.size = 1;
   ec = uper_encode(pduType_Cfg_read_req,(void *) &CfgReadReq,PrvtPro_writeout,&key);
   ......

//decode
    ......
    CfgReadReqInfo_t cfgreadReq;
    CfgReadReqInfo_t *cfgreadReq_ptr = &cfgreadReq;
    memset(&cfgreadReq,0 , sizeof(CfgReadReqInfo_t));
    fprintf(stdout, "appdata length = %d\n",LeMessageDataLen - LeMessageData[0]);
    dc = uper_decode(asn_codec_ctx,pduType_Cfg_read_req,(void *) &cfgreadReq_ptr, \ 							 
            &LeMessageData[LeMessageData[0]],LeMessageDataLen - LeMessageData[0],0,0);
    ......
    fprintf(stdout,"RxAppdata.cfgread.setID.size = %d \r\n",cfgreadReq_ptr->settingIds.list.size);
    fprintf(stdout,"RxAppdata.cfgread.setID = %ld \r\n",(*((cfgreadReq_ptr)->settingIds.list.array))[0].id);
    fprintf(stdout,"RxAppdata.cfgread.setID = %ld \r\n",(*((cfgreadReq_ptr)->settingIds.list.array))[1].id);
    fprintf(stdout,"RxAppdata.cfgread.setID = %ld \r\n",(*((cfgreadReq_ptr)->settingIds.list.array))[2].id);

//print result
RxAppdata.cfgread.setID.size = 4 
RxAppdata.cfgread.setID = 2 
RxAppdata.cfgread.setID = 0 
RxAppdata.cfgread.setID = 0

**Comment by Xjianjian** [comment]
//supplementary instruction
the version of my using is  asn1c-0.9.28.tar.gz

**Comment by velichkov** [comment]
Hi @Xjianjian,

> struct SettingID SetID[255];
> struct SettingID *SetID_ptr = SetID;
> SetID[0].id = 2;
> SetID[1].id = 2;
> SetID[2].id = 3;
> CfgReadReq.settingIds.list.array = &SetID_ptr;
> CfgReadReq.settingIds.list.count = 1;
> CfgReadReq.settingIds.list.size = 1;

You set `count` and `size` to `1` but expect to get `3` elements. Better use the `ASN_SEQUENCE_ADD` macro and do not modify the `list` manually. Also see my [stackoverflow answer](https://stackoverflow.com/questions/56019134/how-to-correctly-use-and-free-asn1c-sequence-of/56028226#56028226)

**Comment by Xjianjian** [comment]
@Velichkov thanks for your reply!

**Comment by Xjianjian** [comment]
CfgReadReqInfo_t CfgReadReq;
memset(&CfgReadReq,0 , sizeof(CfgReadReqInfo_t));
struct SettingID SetID[255];
struct SettingID *SetID_ptr = SetID;
SetID[0].id = 2;
SetID[1].id = 2;
SetID[2].id = 3;
CfgReadReq.settingIds.list.array = &SetID_ptr;
CfgReadReq.settingIds.list.count = 1;
CfgReadReq.settingIds.list.size = ### 3;

**Comment by Xjianjian** [comment]
@velichkov thanks for your reply!
I was woring.The actual way to code is
struct SettingID SetID[255];
struct SettingID *SetID_ptr = SetID;
SetID[0].id = 2;
SetID[1].id = 2;
SetID[2].id = 3;
CfgReadReq.settingIds.list.array = &SetID_ptr;
CfgReadReq.settingIds.list.count = 1;
CfgReadReq.settingIds.list.size = 3;

**Comment by velichkov** [comment]
> I was woring.The actual way to code is

As I said  better use the `ASN_SEQUENCE_ADD` macro and if it sill does not work please share the whole code ready to be compiled together with all commands that you've used to compile it and not just code snippets.

Also please close this issue once you solve this problem.

**Comment by Xjianjian** [comment]
thanks for your reply! thank you!
my problem is still exist，and I don't know how to use the ASN_SEQUENCE_ADD macro.

#include <sys/types.h>
#include <sysexits.h>	/* for EX_* exit codes */
#include <assert.h>	/* for assert(3) */
#include "constr_TYPE.h"
#include "OCTET_STRING.h"
#include "asn_codecs.h"
#include "asn_application.h"
#include "asn_internal.h"	/* for _ASN_DEFAULT_STACK_MAX */
#include "SettingID.h"
#include "CfgReadReqInfo.h"
#include "per_encoder.h"
#include "per_decoder.h"

struct PP_key_t
{
	uint8_t buf[512];
	int size;
};

struct PP_key_t PP_key;

static int PrvtProt_writeout(const void *buffer,size_t size,void *key)
{
	int i;
	struct PP_key_t *key_ptr = (struct PP_key_t*)key;
	if(size > PP_ECDC_DATA_LEN)
	{
		fprintf(stderr, "the size of data greater than PP_MSG_DATA_LEN\n");
		return 0;
	}

	for(i = 0;i < size;i++)
	{
		key_ptr->buf[i] = ((unsigned char *)buffer)[i];
	}
	key_ptr->size=size;
	return 0;
}

int main(void)
{
	CfgReadReqInfo_t CfgReadReq;
	memset(&CfgReadReq,0 , sizeof(CfgReadReqInfo_t));
	struct SettingID  SetID[3];
	struct SettingID *SetID_ptr = SetID;
	uint8_t key[512] = {0};

	SetID[0].id = 5;
	SetID[1].id = 6;
	SetID[2].id = 2;

	CfgReadReq.settingIds.list.count = 0;
	CfgReadReq.settingIds.list.size = 0;
	for(int i = 0 ; i < 3 ; i++)
	{
		ASN_SEQUENCE_ADD(&CfgReadReq, &SetID[i]);
	}
	asn_enc_rval_t ec;
	ec = uper_encode(&asn_DEF_CfgReadReqInfo,(void *) &CfgReadReq,PrvtProt_writeout,&PP_key);
	if(ec.encoded  == -1)
	{
		fprintf(stdout, "encode fail\n");
		return -1;
	}

	asn_dec_rval_t dc;
	asn_codec_ctx_t *asn_codec_ctx = 0;
	CfgReadReqInfo_t DecodeCRR;
	CfgReadReqInfo_t *DecodeCRR_ptr = &DecodeCRR;
	memset(&DecodeCRR,0 , sizeof(CfgReadReqInfo_t));
	dc = uper_decode(asn_codec_ctx,&asn_DEF_CfgReadReqInfo,(void *) &DecodeCRR_ptr, PP_key.buf,PP_key.size,0,0);
	if(dc.code  != RC_OK)
	{
		fprintf(stdout, "decode fail\n");
	}

	fprintf(stdout,"RxAppdata.cfgread.setID.count = %d \r\n",DecodeCRR.settingIds.list.count);
	for(int j = 0; j < DecodeCRR.settingIds.list.count;j++)
	{
		fprintf(stdout,"setID = %ld \r\n",(*(DecodeCRR.settingIds.list.array))[j].id);
	}
	return 0;
}

run result：
setID.count = 3 
setID = 5 
setID = 0 
setID = 0

**Comment by velichkov** [comment]
Hi @Xjianjian,

Please use [markdown](https://guides.github.com/features/mastering-markdown/) to format your messages.

```
$ gcc -I. -o test test.c 
test.c: In function ‘PrvtProt_writeout’:
test.c:25:36: error: conversion to non-scalar type requested
  struct PP_key_t key_ptr = (struct PP_key_t)key;
                                    ^~~~~~~~
test.c:26:12: error: ‘PP_ECDC_DATA_LEN’ undeclared (first use in this function)
  if(size > PP_ECDC_DATA_LEN)
            ^~~~~~~~~~~~~~~~
```
And that's why I've asked you to provide the full source code and commands to compile it. 
> ```c
>CfgReadReq.settingIds.list.count = 0;
>CfgReadReq.settingIds.list.size = 0;
>```

You don't need this as you initialize the whole struct using `memset` few lines above.

> ```c
> for(int i = 0 ; i < 3 ; i++)
>{
>	ASN_SEQUENCE_ADD(&CfgReadReq, &SetID[i]);
>}
>```

This is the correct way to do it.

>```c
>	fprintf(stdout,"setID = %ld \r\n",(*(DecodeCRR.settingIds.list.array))[j].id);
>```

This is way to complicated and probably buggy, try with 
```c
    fprintf(stdout,"setID = %ld \r\n", DecodeCRR.settingIds.list.array[j]->id);
```

**Comment by Xjianjian** [comment]
Hi @velichkov 
thank you!
as you said
fprintf(stdout,"setID = %ld \r\n", DecodeCRR.settingIds.list.array[j]->id);（this is the correct way）

my problem is solved. thank you very much!thank you!!
