### ISSUE TITLE
J2735 SRM Message unable to decode -- as complete details as I can give

### ISSUE THREAD

**Issue by ursine** [vlm/asn1c#337]
I'm implementing a lot of J2735 messages, and I'm having a similar problem with TIM and with SRM messages.  I'm using the J2735_201603 asn1 file, and converting it.  It generates c/h code fine and I am using it to tear apart SPaT and MAP messages without trouble.  However, when an SRM message comes in.  It fails with this message:

 "value: no CHOICE element given (/Users/bear/j2735-asn1-static-library/src/constr_CHOICE.c:532)"

Here is a hexified version of the binary blob I am trying to decode: 

"001D2671A25CF3FAE603000DD5F496344B9E7F56016E3C67C4041A936771624A39107C232800000000"

Instead of decoding this as a type 29, it decodes it as a type 14608, and blows up.

The asn1.io and python asn1 decoders are able to decode it.  So I'm fairly sure the blob is alright.  Here's what the ASN_DEBUG returns as it works through it...

Processing examples/srm_examples.dsrc
line: {"hexlified": "001D2671A25CF3FAE603000DD5F496344B9E7F56016E3C67C4041A936771624A39107C232800000000"}
Decoding MessageFrame as SEQUENCE (UPER) (/home/bear/j2735-asn1-static-library/src/constr_SEQUENCE.c:1098)
  [PER got  1<=72 bits => span 1 +0[1..72]:39 (71) => 0x0] (/home/bear/j2735-asn1-static-library/src/asn_bit_data.c:139)
Decoding member "messageId" in MessageFrame (/home/bear/j2735-asn1-static-library/src/constr_SEQUENCE.c:1170)
Decoding NativeInteger DSRCmsgID (UPER) (/home/bear/j2735-asn1-static-library/src/NativeInteger.c:268)
Integer with range 15 bits (/home/bear/j2735-asn1-static-library/src/INTEGER.c:629)
  [PER got 15<=71 bits => span 16 +0[16..72]:39 (56) => 0x3910] (/home/bear/j2735-asn1-static-library/src/asn_bit_data.c:139)
Got value 14608 + low 0 (/home/bear/j2735-asn1-static-library/src/INTEGER.c:651)
NativeInteger DSRCmsgID got value 14608 (/home/bear/j2735-asn1-static-library/src/NativeInteger.c:285)
Freeing INTEGER as a primitive type (/home/bear/j2735-asn1-static-library/src/asn_codecs_prim.c:125)
Decoding member "value" in MessageFrame (/home/bear/j2735-asn1-static-library/src/constr_SEQUENCE.c:1170)
Failed to decode element MessageFrame (/home/bear/j2735-asn1-static-library/src/OPEN_TYPE.c:310)
Failed decode value in MessageFrame (/home/bear/j2735-asn1-static-library/src/constr_SEQUENCE.c:1180)
Failed processing examples/srm_examples.dsrc -- value: no CHOICE element given (/home/bear/j2735-asn1-static-library/src/constr_CHOICE.c:532)

Is this an issue in the UPER decoding of this message?

**Comment by brchiu** [comment]
@ursine , you can have a trial with https://github.com/mouse07410/asn1c/tree/vlm_master

**Comment by ursine** [comment]
Thanks for the suggestion.  I tried that fork, and a number of files were generated somewhat differently.  Unfortunately, it fails in the same way.  I'm going to single step through the generated code today and see where it breaks.  I've decoded the first few bytes manually so hopefully it'll be fairly easy to find where it goes south.

**Comment by ursine** [comment]
Turned out to be an error on my part.  Sorry for the false alarm.
