### ISSUE TITLE
"syntax error, unexpected TOK_PPEQ, expecting TOK_DEFINITIONS" for 1 line of asn file

### ISSUE THREAD

**Issue by fei4xu** [vlm/asn1c#338]
Hi,

I'm trying to use asn1c and created a new .asn file with 1 line of code:
```asn1
MsgCount ::= INTEGER (0..127)
```
Then I try to compile it 
```
asn1c -E file.asn
```
But I got:
>ASN.1 grammar parse error near file.asn:1 (token "::="): syntax error, unexpected TOK_PPEQ, expecting TOK_DEFINITIONS
Cannot parse "file.asn"

I think my asn file is valid, isn't it?

I'm using the master branch, compiled in Ubuntu.

**Comment by brchiu** [comment]
@fei4xu, your file.asn is not valid. 

```
Test DEFINITIONS ::= BEGIN
MsgCount ::= INTEGER (0..127)
END

```
