### ISSUE TITLE
Can't parse extension group in choice 

### ISSUE THREAD

**Issue by blackDragonReady** [vlm/asn1c#348]
I used asn1c to parse 3gpp 38331(version 15.6) asn1 file. Asn1c reported the following errors:
 **ASN.1 grammar parse error near 38331-f60.asn:4368 (token "[["): syntax error, unexpected TOK_VBracketLeft**

I found the error was connected to the following

```
ReportConfigNR ::=                          SEQUENCE {
    reportType                                  CHOICE {
        periodical                                  PeriodicalReportConfig,
        eventTriggered                              EventTriggerConfig,
        ...,
        reportCGI                                   ReportCGI,
        [[
        reportSFTD                                  ReportSFTD-NR
        ]]
    }
}
```

When i removed [[ and ]]， the file can be parsed

**Comment by velichkov** [comment]
Hi @blackDragonReady,

> I used asn1c to parse 3gpp 38331(version 15.6) asn1 file. Asn1c reported the following errors:
> **ASN.1 grammar parse error near 38331-f60.asn:4368 (token "[["): syntax error, unexpected TOK_VBracketLeft**

Which `asn1c` version do you use?

Try with `velichkov_s1ap_plus_option_group` branch from [brchiu's fork](https://github.com/brchiu/asn1c/tree/velichkov_s1ap_plus_option_group) or `vlm_master` branch from [mouse07410's fork](https://github.com/mouse07410/asn1c/tree/vlm_master)

See also #331, #317 and #238

**Comment by blackDragonReady** [comment]
@velichkov 
I used version b361194 from [master](https://github.com/vlm/asn1c/).
As you saied, I tried the version from [mouse07410's fork](https://github.com/mouse07410/asn1c/tree/vlm_master), the Probelms was resolved. 
Thanks!
