### ISSUE TITLE
Unable to encode in OER format

### ISSUE THREAD

**Issue by vashishthadeexa** [vlm/asn1c#361]
Hi,

I am trying to encode a 1609.2 based certificate in OER format.
I have compiled the asn file using command : asn1c -Wdebug-compiler -fcompound-names -findirect-choice -pdu=all std1609dot2.asn

I am compiling the main file with command: cc -o rencode -DPDU=CertificateBase -DASN_EMIT_DEBUG=1  -Iskeleton_security skeleton_security/*.c main.c

At run time the error displayed at console is: 
OER encoder invoked for (null)
Segmentation fault (core dumped)

I am new to this. Can anyone help?

**Comment by velichkov** [comment]
Hi @vashishthadeexa,

> OER encoder invoked for (null)

Most probably you are calling `oer_encode` with an incorrect type descriptor as it prints `(null)` instead of the type's name.

https://github.com/vlm/asn1c/blob/fdb68ce2782423ce38caf84f28441d1b0776e9ee/skeletons/oer_encoder.c#L12-L14

**Comment by vashishthadeexa** [comment]
Yes. Solved. Thanks.
