### ISSUE TITLE
Unable to decode ITS message IVIM from TS 19321 with asn1c - failed to decode optional part

### ISSUE THREAD

**Issue by sandman** [vlm/asn1c#377]
Hello,
I have been trying to decode a UPER encoded ITS message called IVIM Infrastructure to Vehicle Information Message using asn1c without much success.

The official schema is available here: https://standards.iso.org/iso/ts/19321/ed-2/en/ISO19321(2019)IVIv2.asn

I get the following error when I try to decode the message, which unfortunately does not tell me why the decoding fails. Note that I have compiled the decoder program with debug mode enabled:

`
Decoding member "optional" in IviStructure (constr_SEQUENCE.c:1170)
  [PER got  3<=1322 bits => span 201 +8[9..1328]:1b (1319) => 0x7] (asn_bit_data.c:139)
Preparing to fetch 7+1 elements from IviContainers (constr_SET_OF.c:949)
SET OF IviContainer decoding (constr_SET_OF.c:967)
  [PER got  1<=1319 bits => span 202 +9[2..1320]:d2 (1318) => 0x1] (asn_bit_data.c:139)
  [PER got  7<=1318 bits => span 209 +9[9..1320]:d2 (1311) => 0x25] (asn_bit_data.c:139)
Failed to decode element IviContainer (constr_CHOICE.c:882)
IviContainers SET OF IviContainer decoded 2, 0x55b096f4e7b0 (constr_SET_OF.c:971)
Failed decoding IviContainer of IviContainers (SET OF) (constr_SET_OF.c:986)
Freeing IviContainer as CHOICE (constr_CHOICE.c:1065)
Failed decode optional in IviStructure (constr_SEQUENCE.c:1180)
Failed decode ivi in IVI (constr_SEQUENCE.c:1180)
AD: decode(0) consumed 0+0b (190), code 2
`

The full decoder output is attached: [output.txt](https://github.com/vlm/asn1c/files/4563719/output.txt)

The relevant part of the ASN.1 schema is below:
`IviStructure::= SEQUENCE{
    mandatory       IviManagementContainer,
    optional        IviContainers OPTIONAL
    }

IviContainers ::= SEQUENCE (SIZE (1..8,...)) OF IviContainer

--Definition of Containers

IviContainer::= CHOICE {
    glc     GeographicLocationContainer,
    giv     GeneralIviContainer,
    rcc     RoadConfigurationContainer,
    tc      TextContainer,
    lac     LayoutContainer,
    ...,    -- original extension indicator of V1
[[ -- Extension in V2
    avc     AutomatedVehicleContainer,  
    mlc     MapLocationContainer, 
    rsc     RoadSurfaceContainer ]]
    }
`

Any help to debug the issue is much appreciated!

**Comment by sandman** [comment]
Anyone? I'm kind of at a roadblock here..

**Comment by riebl** [comment]
I believe this issue is related to #407 because IVIM message format uses also extensions markers in size constraints such as `IviContainers ::= SEQUENCE (SIZE (1..8,...)) OF IviContainer`.
@sandman Have you found a fix or simply abandoned asn1c when closing this issue ticket?
