### ISSUE TITLE
Function SET_OF_encode_uper() is missing

### ISSUE THREAD

**Issue by sancane** [vlm/asn1c#42]
I know that this issue was already notified some years ago, but somehow it is not opened here and it is not fixed yet. Perhaps it has been missed when the project moved from sourceforge to github.

Function prototype SET_OF_encode_uper() is defined in constr_SET_OF.h
but does not have a implementation in constr_SET_OF.c resulting in an error on linking time.

SET_OF are nearly the same as SEQUENCE_OF excepting by the order of elements, so SEQUENCE_OF_encode_uper implementation could fix this issue, there are some patches over there like this [1] that could also be applied to master branch.

Regards 

[1]https://gitorious.org/freerdp/mainline/commit/e4bd3ca5681cf76fa948a9c3a0301df5bbcfa813?format=patch

**Comment by xeirwn** [comment]
@sancane, Do you happen to have a copy of the patch that was available at the link you shared?

**Comment by craig65535** [comment]
@sancane @mouse07410 This is in master now.

@vlm Thank you for implementing this. I think this issue can be closed?

**Comment by mouse07410** [comment]
Good work guys! Thanks!
