### ISSUE TITLE
get rrc (not issue)

### ISSUE THREAD

**Issue by ixenion** [vlm/asn1c#448]
Hi vlm!
Could you tell how did you get **rrc-7.1.0.asn1** (asn1c/examples/rrc-7.1.0.asn1) ?
Do you extract it ALL manualy from word document at
https://portal.3gpp.org/desktopmodules/Specifications/SpecificationDetails.aspx?specificationId=1180
Or you used some program which able to extract rrc specs automatically from docx ?

**Comment by mstmob** [comment]
Hi,
have a look at the [proj3rd](https://github.com/proj3rd) project. You can find a extractor and already extracted ASN1 messages in txt and json.

**Comment by ixenion** [comment]
thank you !
