### ISSUE TITLE
How to make f1ap and ngap coexist?

### ISSUE THREAD

**Issue by wujtt** [vlm/asn1c#461]
Hi, I encountered a thorny problem when using ASN tools. Please help me make some suggestions.

As we all konw a partial list of 3GPP protocols using ASN.1, such as **38.413**(NGAP), **38.473**(F1AP). 

F1 message is defined in 3GPP 38.473. NG message is defined in 3GPP 38.413. They belong to two independent but similar ASN files, so using asn1c will generate two sets of. H and. C files.  Some of files generated by asn1c have the same name, and there are even functions with the same name. For example, `InitiatingMessage.h, InitiatingMessage.c, SuccessfulOutcome.h, SuccessfulOutcome.c, ProcedureCode.h, per_decoder.c, per_encoder.c` etc.

Now, I want to develop an application which can process the messages of F1 and NG at the same time. I compiled the .h and .c generated by the ASN files defined by these different protocols into static libraries, so there are now two. a files. When the **static libraries** of f1ap and ngap are loaded in the makefile at the same time, errors will occur in build. Undefined or repeatedly defined problems can be solved by specifying the header file included in the relative path. Such as:
```c++
  #include "../f1asn/include/InitiatingMessage.h"
  #include "../f1asn/include/ProtocolIE-Field.h"
  #include "../f1asn/include/ProtocolExtensionContainer.h"
  #include "../f1asn/include/ProtocolExtensionField.h"
  #include "../f1asn/include/SuccessfulOutcome.h"
  ```

- But when encoding a constructed message after building, since the tool functions of encode has the same name in the two static libraries, only one of the C files with the same name of f1asn and ngasn will be loaded. **This will result in encoding NG messages using the encoding function of f1ap or encoding F1 messages using the encoding function of ngap**

  ```c++
  // When f1ap and ngap are compiled together, the log printed in xer_printf does not correspond to the code. 
  // The key value pair defined in f1ap is used. The include of the header file has been specified with the relative path
  <NGAP-PDU>
      <initiatingMessage>
          <procedureCode>21</procedureCode>
          <criticality><reject/></criticality>
          <value>
              <IABTNLAddressRequest>
                  <protocolIEs>
                  </protocolIEs>
              </IABTNLAddressRequest>
          </value>
      </initiatingMessage>
  </NGAP-PDU>
  
  
  // When ngap is compiled independently, it is correct
  <NGAP-PDU>
      <initiatingMessage>
          <procedureCode>21</procedureCode>
          <criticality><reject/></criticality>
          <value>
              <NGSetupRequest>
                  <protocolIEs>
                  </protocolIEs>
              </NGSetupRequest>
          </value>
      </initiatingMessage>
  </NGAP-PDU>
  
  ```
  
  ```shell
  # When f1ap and ngap are compiled together
  ../../../f1asn/libf1asncodec.a
  (../../../f1asn/libf1asncodec.a)F1AP-PDU.o
  (../../../f1asn/libf1asncodec.a)InitiatingMessage.o
  (../../../f1asn/libf1asncodec.a)SuccessfulOutcome.o
  (../../../f1asn/libf1asncodec.a)UnsuccessfulOutcome.o
  ......
  (../../..//f1asn/libf1asncodec.a)per_decoder.o
  (../../../f1asn/libf1asncodec.a)per_encoder.o
  (../../../f1asn/libf1asncodec.a)per_opentype.o
  ......
  
  # The encode function of f1ap is comment in the source file
  ../../../ngasn/libngapasncodec.a
  (../../../ngasn/libngapasncodec.a)NGAP-PDU.o
  (../../../ngasn/libngapasncodec.a)InitiatingMessage.o
  (../../../ngasn/libngapasncodec.a)SuccessfulOutcome.o
  (../../../ngasn/libngapasncodec.a)UnsuccessfulOutcome.o
  ......
  (../../../ngasn/libngapasncodec.a)constr_CHOICE.o
  (../../../ngasn/libngapasncodec.a)constr_SEQUENCE.o
  (../../../ngasn/libngapasncodec.a)constr_SEQUENCE_OF.o
  (../../../ngasn/libngapasncodec.a)constr_SET_OF.o
  (../../../ngasn/libngapasncodec.a)constr_TYPE.o
  (../../../ngasn/libngapasncodec.a)per_encoder.o
  ......
  ```
Use  -Wl,--verbose in load library in build, we can see which file is loaded. We can see that the files with the same name mentioned above are **different** in different situations. The **encode function** and the related. C files of which side are loaded determine which ASN is used for encoding. This results in different running results. The former results in encoding NG message but displaying IE name of F1, while the latter can display normally.
 
### So my question is:
- Can make f1ap and ngap coexist?
- How to make files with the same name and functions with the same name coexist in f1asn and ngasn?

**Comment by wujtt** [comment]
Can this tool prefix files when generating them? Including file name, variable name, etc

**Comment by velichkov** [comment]
Hi @wujtt,

> Can this tool prefix files when generating them? Including file name, variable name, etc

Yes, the version in `vlm_master` branch from [mouse07410's fork](https://github.com/mouse07410/asn1c/tree/vlm_master) supports prefixing, see b8a6be0aed5ba7d8608277971ca02a2b8ce812d4

**Comment by wujtt** [comment]
OK，thanks very much.
