### ISSUE TITLE
ASN1C compiler error while compiling 

### ISSUE THREAD

**Issue by chetanpandey1266** [vlm/asn1c#478]
Hi 
I am trying to compile multiple file using asn1c where one file imports ASN1 modules from another. But when I am doing so I am getting:

```shell
FATAL: Cannot find external module "..." mentioned for "..." at line ... Obtain this module and instruct compiler to process it.
```

What I am doing is keeping all the files in a directory and running

```shell
asn1c *.asn
```

**Comment by attina** [comment]
@chetanpandey1266 Could you share how you managed fix this problem?

**Comment by chetanpandey1266** [comment]
If I remember clearly this was happening because all the includes in c files were with `<>` which mean the directory where the file is present should be known to the compiler, that you can set in `Makefile` or else just use 

```shell
asn1c *asn -fincludes-quoted
```
