### ISSUE TITLE
Is this library actually working?

### ISSUE THREAD

**Issue by chetanpandey1266** [vlm/asn1c#481]
I tried the latest release of this library and followed the doc to generate the encoder and decoder for the `Rectangle.asn` but it is giving me a lot of errors :
<img width="969" alt="image" src="https://github.com/vlm/asn1c/assets/55939332/a865039f-ada2-4a74-8470-b7326a4c954d">
<img width="951" alt="image" src="https://github.com/vlm/asn1c/assets/55939332/04dd6984-3ea0-4efb-913a-7307842141b1">

Then I also tried the master branch but I am not able to build the branch as it is giving: cannot find input file: 'tests/tests-c-compiler/check-src/Makefile.in'

**Comment by chetanpandey1266** [comment]
If there are some other better alternatives please suggest

**Comment by velichkov** [comment]
Hi @chetanpandey1266,

Yes, it works. It does not support all modern ASN.1 features but for what it supports it works quite well.

Looks like you are compiling it with a `c++` compiler (probably g++). You need to compile it with `c` compiler (gcc) as `c++` is much stricter when it comes to casts from one type to another.  You also need to install gcc header as you are missing `sysexits.h` header file.

**Comment by chetanpandey1266** [comment]
Yeah I was using a cpp compiler. My bad
