### ISSUE TITLE
Unable to parse the asn file for mms in wireshark because it references an external structure

### ISSUE THREAD

**Issue by shuimoshusheng** [vlm/asn1c#488]
IMPORTS
        EXTERNALt,
	AP-title,
	AP-invocation-identifier,
	AE-qualifier,
    AE-invocation-identifier
FROM ISO-8650-ACSE-1;

Source File Link[https://github.com/wireshark/wireshark/blob/4d71744d84cb9e5075b788ab1ff2fca793be8bbd/epan/dissectors/asn1/mms/mms.asn](url)

**Comment by chetanpandey1266** [comment]
You need to get all the files including the ones which defines the external structure and then run `asn1c *.asn`

**Comment by shuimoshusheng** [comment]
> You need to get all the files including the ones which defines the external structure and then run `asn1c *.asn`

Thanks！I'll try it.
