### ISSUE TITLE
Output files list all but the last flag in their comments

### ISSUE THREAD

**Issue by Ymbirtt** [vlm/asn1c#55]
At the top of each .c and .h file generated by asn1c, there is a commented line like `asn1c -fcompound-names`, ostensibly showing the options used to generate them. This information is slightly misleading, however, since the last option is always missing; running `asn1c -fcompound-names -fno-include-deps *.asn` will produce a comment in each file reading `asn1c -fcompound-names`.

**Comment by vlm** [comment]
Fixed, thank you!
