### ISSUE TITLE
Compilation issue -- AM_PROG_AR missing

### ISSUE THREAD

**Issue by fclaerho** [vlm/asn1c#62]
Hello!

I get those errors while compiling the project (ubuntu 14.04, x64); automake is nice enough to suggest the fix :-)

	(...)
	automake: warnings are treated as errors
	/usr/share/automake-1.14/am/ltlibrary.am: warning: 'libasn1compiler.la': linking libtool libraries using a non-POSIX
	/usr/share/automake-1.14/am/ltlibrary.am: archiver requires 'AM_PROG_AR' in 'configure.ac'
	libasn1compiler/Makefile.am:8:   while processing Libtool library 'libasn1compiler.la'
	/usr/share/automake-1.14/am/ltlibrary.am: warning: 'libasn1fix.la': linking libtool libraries using a non-POSIX
	/usr/share/automake-1.14/am/ltlibrary.am: archiver requires 'AM_PROG_AR' in 'configure.ac'
	libasn1fix/Makefile.am:6:   while processing Libtool library 'libasn1fix.la'
	/usr/share/automake-1.14/am/ltlibrary.am: warning: 'libasn1parser.la': linking libtool libraries using a non-POSIX
	/usr/share/automake-1.14/am/ltlibrary.am: archiver requires 'AM_PROG_AR' in 'configure.ac'
	libasn1parser/Makefile.am:6:   while processing Libtool library 'libasn1parser.la'
	/usr/share/automake-1.14/am/ltlibrary.am: warning: 'libasn1print.la': linking libtool libraries using a non-POSIX
	/usr/share/automake-1.14/am/ltlibrary.am: archiver requires 'AM_PROG_AR' in 'configure.ac'
	libasn1print/Makefile.am:7:   while processing Libtool library 'libasn1print.la'
	/usr/share/automake-1.14/am/ltlibrary.am: warning: 'libasn1cskeletons.la': linking libtool libraries using a non-POSIX
	/usr/share/automake-1.14/am/ltlibrary.am: archiver requires 'AM_PROG_AR' in 'configure.ac'
	skeletons/Makefile.am:21:   while processing Libtool library 'libasn1cskeletons.la'
	(...)

**Comment by dunn** [comment]
I get this on Mac OS 10.10.4 too: https://gist.github.com/dunn/5fe1aae3aabf68190f27#file-01-autoreconf-L42

Removing `-Werror` from the `AM_INIT_AUTOMAKE` flags in configure.ac allows it to build and it seems to run fine too, but I'm sure there's a better solution.

**Comment by anatolyborodin** [comment]
#63 can be related.

**Comment by vlm** [comment]
Processed https://github.com/vlm/asn1c/pull/63

**Comment by RahulJain7** [comment]
Installing libtool worked for me
sudo apt intall libtool
