### ISSUE TITLE
Failed to parse X2AP

### ISSUE THREAD

**Issue by wajacps** [vlm/asn1c#64]
I tried to parse the X2AP (from the TS36.423 Rel11.2). Here is the error output:

ASN.1 grammar parse error near line 421 (token "id-E-RAB-Item"): syntax error, unexpected TOK_identifier, expecting '}'
Cannot parse "X2AP-IEs.asn"

I'm using the asn1c version 0.9.27.

**Comment by mkhon** [comment]
asn1c does fully implement Information Object Class spec - it can not parse Information Object Set defintion that uses WITH SYNTAX clause of CLASS definition.




[X2AP-CommonDataTypes.asn.txt](https://github.com/vlm/asn1c/files/115314/X2AP-CommonDataTypes.asn.txt)
[X2AP-Containers.asn.txt](https://github.com/vlm/asn1c/files/115316/X2AP-Containers.asn.txt)
[X2AP-IEs.asn.txt](https://github.com/vlm/asn1c/files/115315/X2AP-IEs.asn.txt)
