### ISSUE TITLE
x64 integer

### ISSUE THREAD

**Issue by kozlosoft** [vlm/asn1c#68]
Hello. 
I'm trying to use compiler with specification with x64 integer and get this error:
Value "18446744073709551615" at line 163 is too large for this compiler! Please contact the asn1c author.
ASN.1 grammar parse error near line 163 (token "18446744073709551615"): syntax error, unexpected $end

asn.1 file was like:
DataContent ::= SEQUENCE {
...
bytes-count        INTEGER (0 .. 18446744073709551615),
...
}

how can I compile huge numbers like this one?

**Comment by vlm** [comment]
If you are using a 64-bit compiler, just remove the constraint. That is not exactly right (this constraint means `uint64_t`), but it should work for the purpose. On 64-bit platforms long means `int64_t`, which won't overflow for most intended use cases for this `bytes-count` field.
