### ISSUE TITLE
Missing parenthesis cause incorrect logic

### ISSUE THREAD

**Issue by pzb** [vlm/asn1c#72]
At https://github.com/vlm/asn1c/blob/master/libasn1compiler/asn1c_C.c#L1778 and 1779, the construct "&& !thing == SOME_CONSTANT".  This should be "&& !(thing == SOME_CONSTANT)" as the ! has higher precedence than the ==.

**Comment by mkhon** [comment]
This one is fixed in this commit: 1b3a135184aa300e25b28b3215debdefb732a6fd

**Comment by vlm** [comment]
Fixed, thank you!
