### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [vlm/asn1c#84]
I would like to point out that identifiers like "[`__i`](https://github.com/vlm/asn1c/blob/6b949bbd7ae00081a510622016f16eaa2b3b48f1/libasn1print/asn1print.c#L12)" and "[`__len`](https://github.com/vlm/asn1c/blob/6b949bbd7ae00081a510622016f16eaa2b3b48f1/libasn1fix/asn1fix_misc.c#L25)" [do eventually not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by vlm** [comment]
Fixed, thank you!

**Comment by elfring** [comment]
There are more update candidates left over.

Examples:
* [`_ASN1FIX_ENUM_H_`](https://github.com/vlm/asn1c/blob/6b949bbd7ae00081a510622016f16eaa2b3b48f1/libasn1fix/asn1fix_enum.h#L1 "Improve include guard")
* `_ASN_CALLBACK`
* [`__ASN_E_cbc`](https://github.com/vlm/asn1c/blob/1ec76055007a79b1568bebc8f9e6ae015262df8c/skeletons/asn_internal.h#L66 "Reconsider identifier selection")

**Comment by vlm** [comment]
Fixed, thank you!

My general stance wrt. these identifiers is that the asn1c generates the code to be used in the application code. As such, the code should be both identifier-wise safe from the environment (C standard) perspective and also not clash with the application code. These two things are mutually incompatible: the libraries are forced to use the application identifier rules (such as no leading underscores, no _t's, etc). So I am not following the rules too pedantically, that is, the _t suffix won't be removed.

I've removed the leading underscores though. Thank you!

**Comment by elfring** [comment]
Would you like to [reconsider the usage of double underscores](http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?") in [affected identifiers](https://github.com/vlm/asn1c/commit/7c1dc05f0e10ede24f577fe4b9fa0fdf8036e1f2#diff-cd88d514f5ef74093cd81e530dfea194R133 "Do not use reserved identifiers") once more?
