### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [vlm/asn1c#85]
Would you like to add more error handling for return values from functions like the following?
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [generate_pdu_C_definition](https://github.com/vlm/asn1c/blob/6b949bbd7ae00081a510622016f16eaa2b3b48f1/libasn1compiler/asn1c_save.c#L545)
- [printf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html "Print formatted output.") ⇒ [asn1print](https://github.com/vlm/asn1c/blob/6b949bbd7ae00081a510622016f16eaa2b3b48f1/libasn1print/asn1print.c#L31)

**Comment by vlm** [comment]
Fixed, thanks!

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more.
Would you like to detect every error situation as early as possible?

How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2FC.2B.2B "Tools for static code analysis") also for this software?
