### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [vlm/asn1c#86]
[An extra null pointer check is not needed](http://pubs.opengroup.org/onlinepubs/9699919799/functions/free.html "Do I need to check for NULL before free(p)?") in functions like the following.
* [asn1p_ioc_row_delete](https://github.com/vlm/asn1c/blob/6b949bbd7ae00081a510622016f16eaa2b3b48f1/libasn1parser/asn1p_class.c#L43)
* [asn1p_module_free](https://github.com/vlm/asn1c/blob/6b949bbd7ae00081a510622016f16eaa2b3b48f1/libasn1parser/asn1p_module.c#L22)

Would you like to apply the following [semantic patch](http://coccinelle.lip6.fr/ "Program transformation with Coccinelle?") to find more update candidates?
```
@Remove_unnecessary_pointer_checks@
expression x;
@@
-if (x)
    free(x);
```

**Comment by vlm** [comment]
Fixed, thanks!

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/vlm/asn1c/commit/d8b8364c8acea078ff098d8b6fbaa0a29da9346a "Deletion of unnecessary null pointer checks").
